### ISSUE TITLE
P_IsoSeqCluster failed. 

### ISSUE THREAD

**Issue by iggyB** [PacificBiosciences/SMRT-Analysis#143]
Hej,

At our core facility we started to run **SMRTAnalysis 2.3** and bumped into some problems. 
Our FAS suggested to get going with "Issues" on git... So here it comes.

The first one is **IsoSeq** pipeline. 

The analysis crashes during **clustering** step. The lates error:
```
2014-11-06 14:48:01,382 [INFO] [Cluster] Checking input files.
2014-11-06 14:48:01,382 [INFO] [Cluster] Checking outputs.
2014-11-06 14:48:01,393 [INFO] [Cluster] A Cluster Object created.
2014-11-06 14:48:01,393 [INFO] [Cluster] Start to run cluster.
2014-11-06 14:48:01,393 [INFO] [Cluster] Splitting /data/userdata/jobs/016/016673/data/isoseq_flnc.fasta into smaller files each containing 20000 reads.
2014-11-06 14:48:03,301 [INFO] [Cluster] Splitted files are: /data/userdata/jobs/016/016673/data/clusterOutDir/input.split_00.fa
2014-11-06 14:48:03,302 [INFO] [Cluster] Loading probabilities and QV from /data/userdata/jobs/016/016673/data/clusterOutDir/input.split_00.fa.
2014-11-06 14:49:44,760 [INFO] [Cluster] Finding maximal cliques: initializing IceInit.
2014-11-06 14:49:44,761 [INFO] Calling blasr /data/userdata/jobs/016/016673/data/clusterOutDir/input.split_00.fa /data/userdata/jobs/016/016673/data/clusterOutDir/input.split_00.fa -m 5
 -maxLCPLength 15 -nproc 8 -maxScore -5000 -bestn 24 -nCandidates 24 -out /data/userdata/jobs/016/016673/data/clusterOutDir/input.split_00.fa.self.blasr
2014-11-06 15:36:09,859 [INFO] [Cluster] Dumping initial clusters to /data/userdata/jobs/016/016673/data/clusterOutDir/init.uc.pickle
2014-11-06 15:36:09,919 [INFO] [Cluster] Iterative clustering: initializing IceIterative.
2014-11-06 15:36:15,007 [ERROR] Exiting pbtranscript with return code 1.
Traceback (most recent call last):
  File "/apps/prod/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/pbtranscript.py", line 145, in run
    obj.run()
  File "/apps/prod/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/Cluster.py", line 222, in run
    probQV=self._probqv)
  File "/apps/prod/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 89, in __init__
    sanity_check_sge(self.script_dir)
  File "/apps/prod/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceUtils.py", line 78, in sanity_check_sge
    if not filecmp.cmp(consensusFa, GCON_OUT_FA):
  File "/apps/prod/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/filecmp.py", line 42, in cmp
    s1 = _sig(os.stat(f1))
OSError: [Errno 2] No such file or directory: '/data/userdata/jobs/016/016673/data/clusterOutDir/scripts/gcon_test_dir/g_consensus.fa'
# Writing stdout and stderr from Popen:
Your job 9614 ("Iclu016673") has been submitted
Job 9614 exited with exit code 1.
```

Job was submitted through the portal to SGE cluster. The comant which failed:
```
# Task 2
pbtranscript.py -v cluster --bas_fofn /data/userdata/jobs/016/016673/input.fofn --ccs_fofn /data/userdata/jobs/016/016673/reads_of_insert.fofn -d /data/userdata/jobs/016/016673/data/clu
sterOutDir --blasr_nproc 8 --unique_id 16673 --cDNA_size above3k --report=/data/userdata/jobs/016/016673/data/isoseq_cluster_info.csv --use_sge --max_sge_jobs 6  --summary=/data/userdat
a/jobs/016/016673/data/cluster_summary.txt --nfl_fa=/data/userdata/jobs/016/016673/data/isoseq_nfl.fasta /data/userdata/jobs/016/016673/data/isoseq_flnc.fasta /data/userdata/jobs/016/01
6673/data/consensus_isoforms.fasta  || exit $?
```

Any quick ideas?
Non quick ideas? :)

Cheers,
Iggy

P.S. I just figured that script **test.sh** is the one that generates **g_consensus.fa**... Wonder why it was not running in the pipeline...

**Comment by pb-jlandolin** [comment]
OK, so it sounds like this is a general distributed computing problem, rather than a IsoSeq or HGAP-specific issue.   you need to check the .tmpl and smrtpipe.rc files:  $SMRT_ROOT/current/analysis/etc/cluster/<JMS>/start.tmpl

https://github.com/PacificBiosciences/SMRT-Analysis/wiki/Distributed-Computing-Configuration


First try to run lambda on single-node:

https://github.com/PacificBiosciences/SMRT-Analysis/wiki/SMRT-Portal-Job-Fails
