### ISSUE TITLE
SmrtAnalysis 2.3 crashing in doSplitBarcodeAmpliconAnalysis

### ISSUE THREAD

**Issue by tzhughes** [PacificBiosciences/SMRT-Analysis#151]
Running on a sample of barcoded amplicons of 12.5 kb (25 barcodes) two FCs of data:
* subreads protocol works fine
* reads of inserts works fine
* long amplicon analysis **crashes**

Any help much appreciated :smile: 

```
[INFO] 2014-11-25 22:03:13,629 [root main 269] Starting smrtpipe.py : v1.87.139483
[INFO] 2014-11-25 22:03:13,630 [root main 270] Using Python : v2.7.3
[INFO] 2014-11-25 22:03:13,638 [root main 271] Platform info Linux-2.6.32-344-ec2-x86_64-with-Ubuntu-10.04-lucid
[INFO] 2014-11-25 22:03:13,640 [root main 272] Running on ip-10-169-66-19.ec2.internal
[INFO] 2014-11-25 22:03:13,640 [root main 273] Process id 17785
[INFO] 2014-11-25 22:03:13,640 [SMRTpipe.pbpy.io.SecondaryConfig _loadFromFile 25] Loading SecondaryConfig from /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/etc/config.xml
[INFO] 2014-11-25 22:03:13,641 [SMRTpipe.SmrtPipeConfig __autoLoad 113] Loading configuration from /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/smrtpipe.rc
[INFO] 2014-11-25 22:03:13,641 [SMRTpipe.SmrtPipeConfig __setAlgorithmParametersPath 212] ALGO_PARAMS key not found in smrtpipe.rc - using latest bundle: /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09
[INFO] 2014-11-25 22:03:13,643 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /opt/smrtanalysis/userdata/inputs_dropbox/2014run31/D01_1/Analysis_Results/m141113_032801_42174_c100645522550000001823116109101433_s1_X0.2.bax.h5 2059778152 bytes
[INFO] 2014-11-25 22:03:13,643 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /opt/smrtanalysis/userdata/inputs_dropbox/2014run31/D01_1/Analysis_Results/m141113_032801_42174_c100645522550000001823116109101433_s1_X0.1.bax.h5 1839311093 bytes
[INFO] 2014-11-25 22:03:13,643 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /opt/smrtanalysis/userdata/inputs_dropbox/2014run31/D01_1/Analysis_Results/m141113_032801_42174_c100645522550000001823116109101433_s1_X0.3.bax.h5 2163349954 bytes
[INFO] 2014-11-25 22:03:13,643 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /opt/smrtanalysis/userdata/inputs_dropbox/2014run31/E01_1/Analysis_Results/m141113_074730_42174_c100645522550000001823116109101434_s1_X0.2.bax.h5 2054225307 bytes
[INFO] 2014-11-25 22:03:13,643 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /opt/smrtanalysis/userdata/inputs_dropbox/2014run31/E01_1/Analysis_Results/m141113_074730_42174_c100645522550000001823116109101434_s1_X0.3.bax.h5 2140037598 bytes
[INFO] 2014-11-25 22:03:13,643 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /opt/smrtanalysis/userdata/inputs_dropbox/2014run31/E01_1/Analysis_Results/m141113_074730_42174_c100645522550000001823116109101434_s1_X0.1.bax.h5 1799024589 bytes
[INFO] 2014-11-25 22:03:13,643 [smrtpipe.status _sanityCheck 804] Successfully found 6 files in xml:/opt/smrtanalysis/userdata/jobs/016/016449/input.xml
[INFO] 2014-11-25 22:03:13,644 [SMRTpipe.pbpy.io.SecondaryConfig _loadFromFile 25] Loading SecondaryConfig from /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/etc/config.xml
[INFO] 2014-11-25 22:03:13,644 [SMRTpipe.SmrtPipeConfig __autoLoad 113] Loading configuration from /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/smrtpipe.rc
[INFO] 2014-11-25 22:03:13,644 [SMRTpipe.SmrtPipeConfig __setAlgorithmParametersPath 212] ALGO_PARAMS key not found in smrtpipe.rc - using latest bundle: /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09
[INFO] 2014-11-25 22:03:13,645 [SMRTpipe.SmrtPipeContext __init__ 98] SmrtPipeConfig Summary:
TMP = /opt/smrtanalysis/tmpdir
PROGRESS_URL = http://107.22.175.191:8080/smrtportal/api
CLUSTER_MANAGER = BASH
HOST_PORT = 8080
NCHUNKS = 64
ALGO_PARAMS_PATH = /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09
MAX_SLOTS = 256
ca_distribute.hgap = useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0
CLOUD_LARGE_FILE_CUTOFF = 10MB
SMRTANALYSIS_VERSION = 2.3.0
INPUT_HDF5_EXT = bas.h5
SMRTPIPE_VERSION = 2.3.0.139497
HOST_NAME = 107.22.175.191
DENOVO_READ_SCOPES = small: 0.15, large:15, huge:1700
NPROC = 1
DENOVO_GENOME_SCOPES = small:100, large:1000, huge:40000
NJOBS = 64
CLOUD = False
REFERENCE_SCOPES = small:10, large:1000, veryLarge:100000, huge:10000000
MAX_THREADS = 8
HEARTBEAT_FREQ = 60
VIS_HOST = 107.22.175.191
VIS_PORT = 8080
SHARED_DIR = /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/common/userdata/shared_dir
DEBUG = False
ca_distribute.pb2ca = useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0
SETTINGS_PATH = .
EXIT_ON_FAILURE = True
CLOUD_CHUNKS_PER_PROC = 2
READ_SCOPES = small:3.6, large:100, veryLarge:10000, huge:1000000
MAX_CHUNKS = 64
ASSEMBLY_HOME = /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis
DATA_ROOT = /mnt
VIS_NAMESPACE =
IPY = ipy -X:ColorfulConsole
TOC_HTML_NAME = index.html
[INFO] 2014-11-25 22:03:13,648 [SMRTpipe.SmrtPipeMain run 465] Successfully found or created TMP dir '/opt/smrtanalysis/tmpdir'
[INFO] 2014-11-25 22:03:13,651 [SMRTpipe.SmrtPipeContext initializeContext 235] SmrtPipeSettings Summary:
settings loaded from file /
p_ampliconanalysis.fastxByBarcode = true
p_ampliconanalysis.ignoreEnds = 0
global.version = 1
p_barcode.mode = paired
global.fetch = common/protocols/preprocessing/Fetch.1.xml
p_fetch.moduleName = P_Fetch
global.barcode = common/protocols/barcode/Barcode.1.xml
p_ampliconanalysis.moduleName = P_AmpliconAnalysis
global.state = active
global.amplicon = common/protocols/consensus/LongAmpliconAnalysis.1.xml
global.control = /opt/smrtanalysis/userdata/references/2kb_control
p_ampliconanalysis.takeN = 0
global.description = (BETA) Determine phased consensus sequences for pooled amplicon data. (Optionally splits reads by barcode if the sample is barcoded.)
p_ampliconanalysis.doPhasing = True
p_barcode.moduleName = P_Barcode
p_ampliconanalysis.minLength = 12000
p_ampliconanalysis.maxReads = 2000
p_barcode.score = 30
p_barcode.barcode.fasta = common/references/pacbio_barcodes_paired
global.name = RS_Long_Amplicon_Analysis
p_ampliconanalysis.description = LongAmpliconAnalysis calls phased consensus sequences from pooled amplicon sequence data. Up to 20 distinct amplicons can be pooled. Reads are clustered into high-level groups, then each group is phased and consensus is called using the Quiver algorithm. Additionally, if the sample is barcoded, separate calls are made for each barcode.
p_ampliconanalysis.doClustering = True
p_fetch.description = Sets up inputs
p_ampliconanalysis.trimEnds = 0
[INFO] 2014-11-25 22:03:13,652 [SMRTpipe.SmrtDataService setupOutputDirectories 132] Creating /opt/smrtanalysis/userdata/jobs/016/016449/data
[INFO] 2014-11-25 22:03:13,652 [SMRTpipe.SmrtDataService setupOutputDirectories 132] Creating /opt/smrtanalysis/userdata/jobs/016/016449/results
[INFO] 2014-11-25 22:03:13,653 [SMRTpipe.SmrtDataService setupOutputDirectories 136] Completed setting up DataServices in /opt/smrtanalysis/userdata/jobs/016/016449
[INFO] 2014-11-25 22:03:13,653 [SMRTpipe.SmrtPipeContext initializeContext 257] Input data is [ file//opt/smrtanalysis/userdata/inputs_dropbox/2014run31/D01_1, file//opt/smrtanalysis/userdata/inputs_dropbox/2014run31/E01_1 ]
[INFO] 2014-11-25 22:03:13,653 [SMRTpipe.SmrtPipeContext initializeContext 261] Configuration override for PROGRESS_URL: Old: --> New: http://107.22.175.191:8080/smrtportal/api
[INFO] 2014-11-25 22:03:13,653 [SMRTpipe.SmrtPipeContext initializeContext 274] Changing working directory to /opt/smrtanalysis/tmpdir/tmpPJ0eni
[INFO] 2014-11-25 22:03:13,667 [SMRTpipe.SmrtPipeContext movieFiles 371] Pulling data from tags: *
[INFO] 2014-11-25 22:03:13,667 [SMRTpipe.SmrtPipeContext movieFiles 391] Found /opt/smrtanalysis/userdata/inputs_dropbox/2014run31/D01_1/Analysis_Results/m141113_032801_42174_c100645522550000001823116109101433_s1_X0.2.bax.h5 (2059778152 bytes)
[INFO] 2014-11-25 22:03:13,667 [SMRTpipe.SmrtPipeContext movieFiles 391] Found /opt/smrtanalysis/userdata/inputs_dropbox/2014run31/D01_1/Analysis_Results/m141113_032801_42174_c100645522550000001823116109101433_s1_X0.1.bax.h5 (1839311093 bytes)
[INFO] 2014-11-25 22:03:13,668 [SMRTpipe.SmrtPipeContext movieFiles 391] Found /opt/smrtanalysis/userdata/inputs_dropbox/2014run31/D01_1/Analysis_Results/m141113_032801_42174_c100645522550000001823116109101433_s1_X0.3.bax.h5 (2163349954 bytes)
[INFO] 2014-11-25 22:03:13,668 [SMRTpipe.SmrtPipeContext movieFiles 391] Found /opt/smrtanalysis/userdata/inputs_dropbox/2014run31/E01_1/Analysis_Results/m141113_074730_42174_c100645522550000001823116109101434_s1_X0.2.bax.h5 (2054225307 bytes)
[INFO] 2014-11-25 22:03:13,668 [SMRTpipe.SmrtPipeContext movieFiles 391] Found /opt/smrtanalysis/userdata/inputs_dropbox/2014run31/E01_1/Analysis_Results/m141113_074730_42174_c100645522550000001823116109101434_s1_X0.3.bax.h5 (2140037598 bytes)
[INFO] 2014-11-25 22:03:13,668 [SMRTpipe.SmrtPipeContext movieFiles 391] Found /opt/smrtanalysis/userdata/inputs_dropbox/2014run31/E01_1/Analysis_Results/m141113_074730_42174_c100645522550000001823116109101434_s1_X0.1.bax.h5 (1799024589 bytes)
[INFO] 2014-11-25 22:03:13,690 [SMRTpipe.SmrtPipeMain _getBasVersions 413] Detected basH5 versions set(['-v2.3.0'])
[INFO] 2014-11-25 22:03:14,373 [smrtpipe.status run 503] smrtpipe.py running on ip-10-169-66-19
[INFO] 2014-11-25 22:03:14,373 [smrtpipe.status run 519] SMRT Analysis 2.3.0 / SMRTpipe 1.87.139483
[INFO] 2014-11-25 22:03:14,374 [SMRTpipe.SmrtPipeMain run 522] Starting smrtpipe version 1.87.139483
[INFO] 2014-11-25 22:03:14,960 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_Fetch module
[INFO] 2014-11-25 22:03:14,962 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_Fetch v2.4.139483 and validated settings.
[INFO] 2014-11-25 22:03:14,988 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_Barcode module
[INFO] 2014-11-25 22:03:14,989 [SMRTpipe.modules.P_Barcode validateSettings 79] Trying barcode fasta file as reference repo: /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/common/references/pacbio_barcodes_paired
[INFO] 2014-11-25 22:03:14,991 [SMRTpipe.modules.P_Barcode validateSettings 81] Barcode fasta file resolved: /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/common/references/pacbio_barcodes_paired/sequence/pacbio_barcodes_paired.fasta
[INFO] 2014-11-25 22:03:14,993 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_Barcode v1.6.139483 and validated settings.
[INFO] 2014-11-25 22:03:14,993 [SMRTpipe.SmrtPipeMain _loadModules 215] Setting barcodeFasta in ReportService to /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/common/references/pacbio_barcodes_paired/sequence/pacbio_barcodes_paired.fasta
[INFO] 2014-11-25 22:03:14,994 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_AmpliconAnalysis module
[INFO] 2014-11-25 22:03:14,998 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_AmpliconAnalysis v1.12.125061 and validated settings.
[INFO] 2014-11-25 22:03:14,999 [SMRTpipe.SmrtDataService writeTo 424] Writing 6 items to DataStore in {'smrt.data.xmlparam': , 'smrt.output.log': '/opt/smrtanalysis/userdata/jobs/016/016449/log', 'smrt.data.cmdline': >, 'smrt.output.root': '/opt/smrtanalysis/userdata/jobs/016/016449', 'smrt.output.results': '/opt/smrtanalysis/userdata/jobs/016/016449/results', 'smrt.output.data': '/opt/smrtanalysis/userdata/jobs/016/016449/data'}
[INFO] 2014-11-25 22:03:15,000 [SMRTpipe.SmrtPipeMain _runTasks 281] Skipping PreWorkflow as it contains zero tasks
[INFO] 2014-11-25 22:03:15,001 [SMRTpipe.SmrtPipeMain _runTasks 284] Loading 9 tasks into Workflow
[INFO] 2014-11-25 22:03:15,157 [SMRTpipe.SmrtPipeMain _runTasks 298] Executing workflow Workflow
[INFO] 2014-11-25 22:03:15,157 [smrtpipe.status execute 620] Process id 17785
[INFO] 2014-11-25 22:03:20,540 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Fetch/toFofn
[INFO] 2014-11-25 22:03:20,558 [smrtpipe.status refreshTargets 407] task P_Fetch.toFofn successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 0 slots.
[INFO] 2014-11-25 22:03:20,558 [smrtpipe.status refreshTargets 409] Workflow Completion Status 1/9 in ( . 11%) tasks completed.
[INFO] 2014-11-25 22:03:25,586 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Fetch/overviewRpt
[INFO] 2014-11-25 22:03:25,587 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Barcode/labelZMWs
[INFO] 2014-11-25 22:03:25,587 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Fetch/adapterRpt
[INFO] 2014-11-25 22:03:26,986 [smrtpipe.status refreshTargets 407] task P_Fetch.overviewRpt successfully completed (1.00 sec (0.02 min)). freed 1 slots, using 2 slots.
[INFO] 2014-11-25 22:03:26,986 [smrtpipe.status refreshTargets 409] Workflow Completion Status 2/9 in ( .. 22%) tasks completed.
[INFO] 2014-11-25 22:04:13,182 [smrtpipe.status refreshTargets 407] task P_Fetch.adapterRpt successfully completed (47.00 sec (0.78 min)). freed 1 slots, using 1 slots.
[INFO] 2014-11-25 22:04:13,183 [smrtpipe.status refreshTargets 409] Workflow Completion Status 3/9 in ( ... 33%) tasks completed.
[INFO] 2014-11-25 22:08:09,292 [smrtpipe.status refreshTargets 407] task P_Barcode.labelZMWs successfully completed (287.00 sec (4.78 min)). freed 1 slots, using 0 slots.
[INFO] 2014-11-25 22:08:09,293 [smrtpipe.status refreshTargets 409] Workflow Completion Status 4/9 in ( .... 44%) tasks completed.
[INFO] 2014-11-25 22:08:14,316 [smrtpipe.status refreshTargets 419] Starting task://016449/P_AmpliconAnalysis/doSplitBarcodeAmpliconAnalysis
[INFO] 2014-11-25 22:08:14,317 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Barcode/barcodeJsonReport
[INFO] 2014-11-25 22:08:14,317 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Barcode/emitFastqs
[INFO] 2014-11-25 22:08:36,246 [smrtpipe.status refreshTargets 407] task P_Barcode.barcodeJsonReport successfully completed (23.00 sec (0.38 min)). freed 1 slots, using 2 slots.
[INFO] 2014-11-25 22:08:36,247 [smrtpipe.status refreshTargets 409] Workflow Completion Status 5/9 in ( ..... 55%) tasks completed.
[INFO] 2014-11-25 22:12:38,946 [smrtpipe.status refreshTargets 407] task P_Barcode.emitFastqs successfully completed (266.00 sec (4.43 min)). freed 1 slots, using 1 slots.
[INFO] 2014-11-25 22:12:38,946 [smrtpipe.status refreshTargets 409] Workflow Completion Status 6/9 in ( ...... 66%) tasks completed.
[ERROR] 2014-11-26 00:21:48,210 [smrtpipe.status refreshTargets 413] *** Failed task task://016449/P_AmpliconAnalysis/doSplitBarcodeAmpliconAnalysis
[INFO] 2014-11-26 00:21:48,211 [smrtpipe.status execute 627] Found 1 failed tasks.
[INFO] 2014-11-26 00:21:48,211 [smrtpipe.status execute 629] task doSplitBarcodeAmpliconAnalysis FAILED
[ERROR] 2014-11-26 00:21:48,350 [SMRTpipe.SmrtPipeMain run 608] SmrtExit task://016449/P_AmpliconAnalysis/doSplitBarcodeAmpliconAnalysis Failed
Traceback (most recent call last):
File "/opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 571, in run
self._runTasks(pModules)
File "/opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 300, in _runTasks
workflow.execute()
File "/opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeWorkflow.py", line 640, in execute
raise SmrtExit(str(e))
SmrtExit: SmrtExit task://016449/P_AmpliconAnalysis/doSplitBarcodeAmpliconAnalysis Failed
[ERROR] 2014-11-26 00:21:48,351 [SMRTpipe.SmrtPipeMain exit 690] SmrtExit task://016449/P_AmpliconAnalysis/doSplitBarcodeAmpliconAnalysis Failed
[INFO] 2014-11-26 00:21:48,351 [SMRTpipe.SmrtPipeMain exit 692] Beginning exit process
[INFO] 2014-11-26 00:21:48,351 [SMRTpipe.SmrtPipeMain shutdown 716] beginning Shutdown Process
[INFO] 2014-11-26 00:21:48,351 [SMRTpipe.SmrtPipeMain _generate_final_report 651] Writing final TOC page with error message : SmrtExit task://016449/P_AmpliconAnalysis/doSplitBarcodeAmpliconAnalysis Failed
[INFO] 2014-11-26 00:21:48,899 [SMRTpipe.SmrtPipeMain shutdown 752] Completed shutdown gracefully
[INFO] 2014-11-26 00:21:48,899 [SMRTpipe.SmrtPipeMain exit 702] Sending message Exiting smrtpipe last error: SmrtExit task://016449/P_AmpliconAnalysis/doSplitBarcodeAmpliconAnalysis Failed
[INFO] 2014-11-26 00:21:48,900 [smrtpipe.status failed 104] Sending Job 016449 failed message 'Exiting smrtpipe last error: SmrtExit task://016449/P_AmpliconAnalysis/doSplitBarcodeAmpliconAnalysis Failed' to url http://107.22.175.191:8080/smrtportal/api/jobs/016449/status
[INFO] 2014-11-26 00:21:48,914 [SMRTpipe.SmrtPipeMain run 641] completed SmrtPipeMain.run with exit code -1
[INFO] 2014-11-26 00:21:48,914 [root main 335] Failed smrtpipe version v1.87.139483 with exit code -1 in 8315.27 seconds (138.59 minutes)
```

**Comment by pb-jlandolin** [comment]
25 barcodes is very few, and you may be overloading the clustering step with too many sequences.  You can try changing the "maximum number of reads" parameter in the LongAmplicon protocol to something more reasonable like 500.   

The RS_LongAmpliconAnalysis algorithm is very sensitive to overloading and will run into memory issues.  You can imagine that it is impossible to have default parameters that universally work for a dataset with ~400 clusters as well as a dataset with ~10 barcoded clusters.
