### ISSUE TITLE
AHA scaffolder IndexError

### ISSUE THREAD

**Issue by jiaocathy** [PacificBiosciences/SMRT-Analysis#153]
Hello,

I am trying to run "pbahaScaffolder.py" to do some scaffolding on very small data. But I got an error said "IndexError: list index out of range". Could you provide any suggestion how to solve this problem? Thank you!

Here is my command line:
"~/software/SMRT-Analysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/bin/python ~/software/SMRT-Analysis/install/smrtanalysis_2.3.0.140936/analysis/bin/pbahaScaffolder.py --debug --tmpDir  /sonas-hs/ware/hpc/data/yjiao/pacbio/order_contigs/test  --maxIterations 1 --outputDir ./  test.bac.hit.fasta test.bac.fa"

Here is the error:
2014-12-06 14:36:21,228 [INFO] Running sort -k3 -t "_" /sonas-hs/ware/hpc/data/yjiao/pacbio/order_contigs/test/pbahawRBYmj/scaffold0/clean_align.rm4_RS > /sonas-hs/ware/hpc/data/yjiao/pacbio/order_contigs/test/pbahawRBYmj/scaffold0/clean_align.rm4_RS.sorted:
2014-12-06 14:36:21,279 [INFO] successfully completed command in 0.05 sec.
2014-12-06 14:36:21,280 [INFO] Running bambus scaffolder
2014-12-06 14:36:21,316 [INFO] Found and kept 3 links
2014-12-06 14:36:21,320 [INFO] Running goBambus -C bambus.conf -c bambus.contigs -m bambus.strobe
2014-12-06 14:36:21,949 [INFO] Creating linear graph
Traceback (most recent call last):
  File "/sonas-hs/ware/hpc/home/yjiao/software/SMRT-Analysis/install/smrtanalysis_2.3.0.140936/analysis/bin/pbahaScaffolder.py", line 5, in <module>
    pkg_resources.run_script('pbaha==0.1.0', 'pbahaScaffolder.py')
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 489, in run_script
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 1207, in run_script
  File "/sonas-hs/ware/hpc/home/yjiao/software/SMRT-Analysis/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/pbaha-0.1.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pbahaScaffolder.py", line 146, in <module>
    sys.exit(main())
  File "/sonas-hs/ware/hpc/home/yjiao/software/SMRT-Analysis/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/pbaha-0.1.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pbahaScaffolder.py", line 135, in main
    state = aha.run()
  File "/sonas-hs/ware/hpc/home/yjiao/software/SMRT-Analysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbaha-0.1.0-py2.7-linux-x86_64.egg/pbaha/main.py", line 517, in run
    returnDict = self._scaffoldIteration(*inputArgs)
  File "/sonas-hs/ware/hpc/home/yjiao/software/SMRT-Analysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbaha-0.1.0-py2.7-linux-x86_64.egg/pbaha/main.py", line 652, in _scaffoldIteration
    BAMBUS_SUMMARY_GML)
  File "/sonas-hs/ware/hpc/home/yjiao/.local/lib/python2.7/site-packages/networkx/readwrite/graphml.py", line 107, in write_graphml
    d = G.edges(data=True)[0][2] # data of first edge
IndexError: list index out of range

**Comment by pb-jlandolin** [comment]
Sorry, we do not support command-line usage until you can demonstrate that the equivalent job can be run through SMRT Portal (RS_AHA_Scaffolding).  This is b/c the command-line options are constantly in flux, and are not always functional.  
 
After running through SMRT Portal, all the command-line calls used to run the pipeline are stored in the workflow directory of the job.  A good trick is to look there for the correct usage of any underlying executable in analysis bin.  That should point you to the correct usage.
