### ISSUE TITLE
Quiver "AttributeError"

### ISSUE THREAD

**Issue by jiaocathy** [PacificBiosciences/SMRT-Analysis#163]
Hello,

I am trying to run Quiver from smrtanalysis_2.3.0. But I got an error.
Here is my command line: 
quiver  test.cmp.h5 -r test.fasta -o test.gff -o test.consensus.fasta 

The error message is here:
Traceback (most recent call last):
  File "/sonas-hs/ware/hpc/home/yjiao/software/SMRT-Analysis/install/smrtanalysis_2.3.0.140936/analysis/bin/variantCaller.py", line 5, in <module>
    sys.exit(main())
  File "/sonas-hs/ware/hpc/home/yjiao/.local/lib/python2.7/site-packages/GenomicConsensus-0.8.0-py2.7.egg/GenomicConsensus/main.py", line 350, in main
    return ToolRunner().main()
  File "/sonas-hs/ware/hpc/home/yjiao/.local/lib/python2.7/site-packages/GenomicConsensus-0.8.0-py2.7.egg/GenomicConsensus/main.py", line 280, in main
    self._configureAlgorithm(options, peekCmpH5)
  File "/sonas-hs/ware/hpc/home/yjiao/.local/lib/python2.7/site-packages/GenomicConsensus-0.8.0-py2.7.egg/GenomicConsensus/main.py", line 181, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, cmpH5)
  File "/sonas-hs/ware/hpc/home/yjiao/.local/lib/python2.7/site-packages/GenomicConsensus-0.8.0-py2.7.egg/GenomicConsensus/quiver/quiver.py", line 274, in configure
    parameterSets=params)
  File "/sonas-hs/ware/hpc/home/yjiao/.local/lib/python2.7/site-packages/GenomicConsensus-0.8.0-py2.7.egg/GenomicConsensus/quiver/model.py", line 322, in __init__
    qct.insert(chem, pset.ccQuiverConfig)
AttributeError: 'QuiverConfigTable' object has no attribute 'insert'

**Comment by pb-jlandolin** [comment]
We do not support stand-alone command-line calls to the underlying tools such as quiver. This is because the code base changes very quickly and the options and input requirements are also in flux. 

What I can recommend you do, is to run a RS_Resequencing job in SMRT Portal, and look at the commands executed by SMRT Portal in the jobid/workflow/P_GenomicConsensus directory. You will notice that we do not use the "quiver" executable, but instead, call "variantCaller.py --algorithm=quiver". 

We encourage you to run job through RS_Resequencing in SMRT Portal first and demonstrate that you can analyze this in the normal and supported workflow before venturing to the command-line.

**Comment by pb-jchin** [comment]
I think what Jean means that the quiver command line is supported by the community and the developers when they are free of other duties. The tech support team only focuses on the production software.
