### ISSUE TITLE
SMRTAnalysis failed to submit job

### ISSUE THREAD

**Issue by cmangat** [PacificBiosciences/SMRT-Analysis#180]
Hi, I'm running smrtanalysis 2.3.0.140936 on to assemble bacterial genomes using HGAP.3.  Our first job worked great, but every subsequent job has failed.  Below is are the log files for a failed job.  Any help is appreciated.

**smrtpipe.stderr**
'NoneType' object has no attribute '_state'

**smrtpipe.stdout**
[INFO] 2015-02-20 12:03:06,227 Successfully found 3 files in xml:/Warehouse/Applications/smrtanalysis/userdata/jobs/016/016446/input.xml
Failed smrtpipe version v1.87.139483 with exit code -1 in 0.01 seconds (0.00 minutes)

**master.log**
[INFO] 2015-02-20 12:03:06,114 [root main 269] Starting smrtpipe.py : v1.87.139483
[INFO] 2015-02-20 12:03:06,114 [root main 270] Using Python         : v2.7.3
[INFO] 2015-02-20 12:03:06,134 [root main 271] Platform info Linux-2.6.32-504.1.3.el6.x86_64-x86_64-with-centos-6.6-Final
[INFO] 2015-02-20 12:03:06,141 [root main 272] Running on smrt.corefacility.ca
[INFO] 2015-02-20 12:03:06,141 [root main 273] Process id 14002
[INFO] 2015-02-20 12:03:06,142 [SMRTpipe.pbpy.io.SecondaryConfig _loadFromFile 25] Loading SecondaryConfig from /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/etc/config.xml
[INFO] 2015-02-20 12:03:06,143 [SMRTpipe.SmrtPipeConfig __autoLoad 113] Loading configuration from /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/smrtpipe.rc
[DEBUG] 2015-02-20 12:03:06,144 [SMRTpipe.SmrtPipeConfig __autoLoad 125] Successfully Autoloaded SmrtPipeConfig from /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/smrtpipe.rc
[INFO] 2015-02-20 12:03:06,146 [SMRTpipe.SmrtPipeConfig __setAlgorithmParametersPath 212] ALGO_PARAMS key not found in smrtpipe.rc - using latest bundle: /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09
[DEBUG] 2015-02-20 12:03:06,147 [SMRTpipe.SmrtPipeMain _sanityCheck 778] Sanity checking of data URL xml:/Warehouse/Applications/smrtanalysis/userdata/jobs/016/016446/input.xml
[DEBUG] 2015-02-20 12:03:06,147 [SMRTpipe.InputData loadXml 208] Loading file /Warehouse/Applications/smrtanalysis/userdata/jobs/016/016446/input.xml
[DEBUG] 2015-02-20 12:03:06,147 [SMRTpipe.pbpy.io.MetaAnalysisXml load 99] Loading /Warehouse/Applications/smrtanalysis/userdata/jobs/016/016446/input.xml
[DEBUG] 2015-02-20 12:03:06,150 [SMRTpipe.pbpy.io.MetaAnalysisXml _parseRef 587] Successfully parsed /Warehouse/Users/cmangat/CRE_PACBIO/UF_RAWDATA/Run_Mulvey_1-30-2015_353/B01_1 to file /Warehouse/Users/cmangat/CRE_PACBIO/UF_RAWDATA/Run_Mulvey_1-30-2015_353/B01_1
[DEBUG] 2015-02-20 12:03:06,150 [SMRTpipe.InputData loadXml 213] loading header from /Warehouse/Applications/smrtanalysis/userdata/jobs/016/016446/input.xml
[DEBUG] 2015-02-20 12:03:06,150 [SMRTpipe.InputData loadXml 218] Initialized CompositeInputData from jobId 016446
[DEBUG] 2015-02-20 12:03:06,150 [SMRTpipe.SmrtPipeMain _sanityCheck 790] checking for [ file//Warehouse/Users/cmangat/CRE_PACBIO/UF_RAWDATA/Run_Mulvey_1-30-2015_353/B01_1 ]
[INFO] 2015-02-20 12:03:06,184 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /Warehouse/Users/cmangat/CRE_PACBIO/UF_RAWDATA/Run_Mulvey_1-30-2015_353/B01_1/Analysis_Results/m150130_211859_42154_c100743142550000001823160206051577_s1_p0.1.bax.h5 3853461185 bytes
[INFO] 2015-02-20 12:03:06,213 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /Warehouse/Users/cmangat/CRE_PACBIO/UF_RAWDATA/Run_Mulvey_1-30-2015_353/B01_1/Analysis_Results/m150130_211859_42154_c100743142550000001823160206051577_s1_p0.3.bax.h5 4142453970 bytes
[INFO] 2015-02-20 12:03:06,227 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /Warehouse/Users/cmangat/CRE_PACBIO/UF_RAWDATA/Run_Mulvey_1-30-2015_353/B01_1/Analysis_Results/m150130_211859_42154_c100743142550000001823160206051577_s1_p0.2.bax.h5 4080434956 bytes
[INFO] 2015-02-20 12:03:06,227 [smrtpipe.status _sanityCheck 804] Successfully found 3 files in xml:/Warehouse/Applications/smrtanalysis/userdata/jobs/016/016446/input.xml
[DEBUG] 2015-02-20 12:03:06,227 [root main 283] Basic sanity checking of xml:/Warehouse/Applications/smrtanalysis/userdata/jobs/016/016446/input.xml successful
[DEBUG] 2015-02-20 12:03:06,227 [SMRTpipe.SmrtPipeMain __init__ 101] SmrtPipeMain called with dataUrl xml:/Warehouse/Applications/smrtanalysis/userdata/jobs/016/016446/input.xml
[INFO] 2015-02-20 12:03:06,227 [SMRTpipe.pbpy.io.SecondaryConfig _loadFromFile 25] Loading SecondaryConfig from /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/etc/config.xml
[INFO] 2015-02-20 12:03:06,228 [SMRTpipe.SmrtPipeConfig __autoLoad 113] Loading configuration from /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/smrtpipe.rc
[DEBUG] 2015-02-20 12:03:06,229 [SMRTpipe.SmrtPipeConfig __autoLoad 125] Successfully Autoloaded SmrtPipeConfig from /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/smrtpipe.rc
[INFO] 2015-02-20 12:03:06,229 [SMRTpipe.SmrtPipeConfig __setAlgorithmParametersPath 212] ALGO_PARAMS key not found in smrtpipe.rc - using latest bundle: /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09
[INFO] 2015-02-20 12:03:06,230 [SMRTpipe.SmrtPipeContext __init__ 98] SmrtPipeConfig Summary:
                         TMP = /Warehouse/Applications/smrtanalysis/tmpdir                                                                     
                PROGRESS_URL = http://smrt.corefacility.ca:8080/smrtportal/api                                                                 
             CLUSTER_MANAGER = SGE                                                                                                             
                   HOST_PORT = 8080                                                                                                            
                     NCHUNKS = 64                                                                                                              
            ALGO_PARAMS_PATH = /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09
                   MAX_SLOTS = 256                                                                                                             
          ca_distribute.hgap = useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0                                                     
     CLOUD_LARGE_FILE_CUTOFF = 10MB                                                                                                            
        SMRTANALYSIS_VERSION = 2.3.0                                                                                                           
              INPUT_HDF5_EXT = bas.h5                                                                                                          
            SMRTPIPE_VERSION = 2.3.0.139497                                                                                                    
                   HOST_NAME = smrt.corefacility.ca                                                                                            
          DENOVO_READ_SCOPES = small: 0.15, large:15, huge:1700                                                                                
                       NPROC = 7                                                                                                               
        DENOVO_GENOME_SCOPES = small:100, large:1000, huge:40000                                                                               
                       NJOBS = 64                                                                                                              
                       CLOUD = False                                                                                                           
            REFERENCE_SCOPES = small:10, large:1000, veryLarge:100000, huge:10000000                                                           
                 MAX_THREADS = 8                                                                                                               
              HEARTBEAT_FREQ = 60                                                                                                              
                    VIS_HOST = smrt.corefacility.ca                                                                                            
                    VIS_PORT = 8080                                                                                                            
                  SHARED_DIR = /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/common/userdata/shared_dir               
                       DEBUG = False                                                                                                           
         ca_distribute.pb2ca = useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0                                                     
               SETTINGS_PATH = .                                                                                                               
             EXIT_ON_FAILURE = True                                                                                                            
       CLOUD_CHUNKS_PER_PROC = 2                                                                                                               
                 READ_SCOPES = small:3.6, large:100, veryLarge:10000, huge:1000000                                                             
                  MAX_CHUNKS = 64                                                                                                              
               ASSEMBLY_HOME = /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis                                 
                   DATA_ROOT = /mnt                                                                                                            
               VIS_NAMESPACE =                                                                                                                 
                         IPY = ipy -X:ColorfulConsole                                                                                          
               TOC_HTML_NAME = index.html                                                                                                      
[ERROR] 2015-02-20 12:03:06,230 [SMRTpipe.SmrtPipeMain run 608] [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 462, in run
    self.context = SmrtPipeContext(self.debug, parent=self, cmdOptions=self.cmdOptions)
  File "/Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeContext.py", line 101, in __init__
    self.settings = SmrtPipeSettings(self.config['SETTINGS_PATH'], self)
  File "/Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeSettings.py", line 39, in __init__
    self.settingsPath = os.path.abspath(settingsPath)
  File "/Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/posixpath.py", line 347, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
[ERROR] 2015-02-20 12:03:06,233 [SMRTpipe.SmrtPipeMain exit 690] [Errno 2] No such file or directory
[INFO] 2015-02-20 12:03:06,233 [SMRTpipe.SmrtPipeMain exit 692] Beginning exit process
[ERROR] 2015-02-20 12:03:06,233 [SMRTpipe.SmrtPipeMain run 614] Error calling .exit. Printing traceback and locals for exception
[DEBUG] 2015-02-20 12:03:06,233 [SMRTpipe.SmrtPipeMain run 620] {'msg': '[Errno 2] No such file or directory', 'self': <SMRTpipe.SmrtPipeMain.SmrtPipeMain object at 0x2c3e990>}
[INFO] 2015-02-20 12:03:06,233 [SMRTpipe.SmrtPipeMain run 641] completed SmrtPipeMain.run with exit code -1
[INFO] 2015-02-20 12:03:06,233 [root main 335] Failed smrtpipe version v1.87.139483 with exit code -1 in 0.01 seconds (0.00 minutes)

**smrtpipe.log**
[INFO] 2015-02-20 12:03:06,114 [root main 269] Starting smrtpipe.py : v1.87.139483
[INFO] 2015-02-20 12:03:06,114 [root main 270] Using Python         : v2.7.3
[INFO] 2015-02-20 12:03:06,134 [root main 271] Platform info Linux-2.6.32-504.1.3.el6.x86_64-x86_64-with-centos-6.6-Final
[INFO] 2015-02-20 12:03:06,141 [root main 272] Running on smrt.corefacility.ca
[INFO] 2015-02-20 12:03:06,141 [root main 273] Process id 14002
[INFO] 2015-02-20 12:03:06,142 [SMRTpipe.pbpy.io.SecondaryConfig _loadFromFile 25] Loading SecondaryConfig from /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/etc/config.xml
[INFO] 2015-02-20 12:03:06,143 [SMRTpipe.SmrtPipeConfig __autoLoad 113] Loading configuration from /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/smrtpipe.rc
[INFO] 2015-02-20 12:03:06,146 [SMRTpipe.SmrtPipeConfig __setAlgorithmParametersPath 212] ALGO_PARAMS key not found in smrtpipe.rc - using latest bundle: /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09
[INFO] 2015-02-20 12:03:06,184 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /Warehouse/Users/cmangat/CRE_PACBIO/UF_RAWDATA/Run_Mulvey_1-30-2015_353/B01_1/Analysis_Results/m150130_211859_42154_c100743142550000001823160206051577_s1_p0.1.bax.h5 3853461185 bytes
[INFO] 2015-02-20 12:03:06,213 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /Warehouse/Users/cmangat/CRE_PACBIO/UF_RAWDATA/Run_Mulvey_1-30-2015_353/B01_1/Analysis_Results/m150130_211859_42154_c100743142550000001823160206051577_s1_p0.3.bax.h5 4142453970 bytes
[INFO] 2015-02-20 12:03:06,227 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /Warehouse/Users/cmangat/CRE_PACBIO/UF_RAWDATA/Run_Mulvey_1-30-2015_353/B01_1/Analysis_Results/m150130_211859_42154_c100743142550000001823160206051577_s1_p0.2.bax.h5 4080434956 bytes
[INFO] 2015-02-20 12:03:06,227 [smrtpipe.status _sanityCheck 804] Successfully found 3 files in xml:/Warehouse/Applications/smrtanalysis/userdata/jobs/016/016446/input.xml
[INFO] 2015-02-20 12:03:06,227 [SMRTpipe.pbpy.io.SecondaryConfig _loadFromFile 25] Loading SecondaryConfig from /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/etc/config.xml
[INFO] 2015-02-20 12:03:06,228 [SMRTpipe.SmrtPipeConfig __autoLoad 113] Loading configuration from /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/smrtpipe.rc
[INFO] 2015-02-20 12:03:06,229 [SMRTpipe.SmrtPipeConfig __setAlgorithmParametersPath 212] ALGO_PARAMS key not found in smrtpipe.rc - using latest bundle: /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09
[INFO] 2015-02-20 12:03:06,230 [SMRTpipe.SmrtPipeContext __init__ 98] SmrtPipeConfig Summary:
                         TMP = /Warehouse/Applications/smrtanalysis/tmpdir                                                                     
                PROGRESS_URL = http://smrt.corefacility.ca:8080/smrtportal/api                                                                 
             CLUSTER_MANAGER = SGE                                                                                                             
                   HOST_PORT = 8080                                                                                                            
                     NCHUNKS = 64                                                                                                              
            ALGO_PARAMS_PATH = /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09
                   MAX_SLOTS = 256                                                                                                             
          ca_distribute.hgap = useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0                                                     
     CLOUD_LARGE_FILE_CUTOFF = 10MB                                                                                                            
        SMRTANALYSIS_VERSION = 2.3.0                                                                                                           
              INPUT_HDF5_EXT = bas.h5                                                                                                          
            SMRTPIPE_VERSION = 2.3.0.139497                                                                                                    
                   HOST_NAME = smrt.corefacility.ca                                                                                            
          DENOVO_READ_SCOPES = small: 0.15, large:15, huge:1700                                                                                
                       NPROC = 7                                                                                                               
        DENOVO_GENOME_SCOPES = small:100, large:1000, huge:40000                                                                               
                       NJOBS = 64                                                                                                              
                       CLOUD = False                                                                                                           
            REFERENCE_SCOPES = small:10, large:1000, veryLarge:100000, huge:10000000                                                           
                 MAX_THREADS = 8                                                                                                               
              HEARTBEAT_FREQ = 60                                                                                                              
                    VIS_HOST = smrt.corefacility.ca                                                                                            
                    VIS_PORT = 8080                                                                                                            
                  SHARED_DIR = /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/common/userdata/shared_dir               
                       DEBUG = False                                                                                                           
         ca_distribute.pb2ca = useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0                                                     
               SETTINGS_PATH = .                                                                                                               
             EXIT_ON_FAILURE = True                                                                                                            
       CLOUD_CHUNKS_PER_PROC = 2                                                                                                               
                 READ_SCOPES = small:3.6, large:100, veryLarge:10000, huge:1000000                                                             
                  MAX_CHUNKS = 64                                                                                                              
               ASSEMBLY_HOME = /Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis                                 
                   DATA_ROOT = /mnt                                                                                                            
               VIS_NAMESPACE =                                                                                                                 
                         IPY = ipy -X:ColorfulConsole                                                                                          
               TOC_HTML_NAME = index.html                                                                                                      
[ERROR] 2015-02-20 12:03:06,230 [SMRTpipe.SmrtPipeMain run 608] [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 462, in run
    self.context = SmrtPipeContext(self.debug, parent=self, cmdOptions=self.cmdOptions)
  File "/Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeContext.py", line 101, in __init__
    self.settings = SmrtPipeSettings(self.config['SETTINGS_PATH'], self)
  File "/Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeSettings.py", line 39, in __init__
    self.settingsPath = os.path.abspath(settingsPath)
  File "/Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/posixpath.py", line 347, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
[ERROR] 2015-02-20 12:03:06,233 [SMRTpipe.SmrtPipeMain exit 690] [Errno 2] No such file or directory
[INFO] 2015-02-20 12:03:06,233 [SMRTpipe.SmrtPipeMain exit 692] Beginning exit process
[ERROR] 2015-02-20 12:03:06,233 [SMRTpipe.SmrtPipeMain run 614] Error calling .exit. Printing traceback and locals for exception
[INFO] 2015-02-20 12:03:06,233 [SMRTpipe.SmrtPipeMain run 641] completed SmrtPipeMain.run with exit code -1
[INFO] 2015-02-20 12:03:06,233 [root main 335] Failed smrtpipe version v1.87.139483 with exit code -1 in 0.01 seconds (0.00 minutes)

**Comment by pb-jlandolin** [comment]
Hi,

The relevant error appears to be:

```
OSError: [Errno 2] No such file or directory
```

If you were able to successfully run a job before, and did  not change the software, it is possible that the underlying file system may have unmounted or changed somehow.  You appear to be using SGE, and might want to ask your cluster admin to mke sure the "Warehouse/Applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/" directory can be read by all nodes and is pointing to the same directory.
