### ISSUE TITLE
AHA blasr command fails during scaffolding

### ISSUE THREAD

**Issue by zfuller5280** [PacificBiosciences/SMRT-Analysis#187]
AHA scaffolding is failing before completion and I get the following error in the master.log file:
`[INFO] 2015-03-18 14:53:13,054 [SMRTpipe.SmrtPipeMain exit 702] Sending message Exiting smrtpipe last error: SmrtExit Failed to find any links. Scaffolding failed.`
However, if I look in the pbaha.log file, it appears that this is not the true error and that something else is failing before:
```
2015-03-18 14:50:28,603 [INFO] Calculating clean alignments
2015-03-18 14:50:28,604 [INFO] Running blasr /nfs/thumper.galaxyproject.org/home/zlf105/Assembly/data/long_filtered_subreads.fasta /nfs/thumper.galaxyproject.org/home/zlf105/Assembly/log/P_AHA/.initial_contigs.fasta -m 4 -minMatch 10 -minPctIdentity 70 -bestn 10 -noSplitSubreads -nproc 16 -out /tmp/smrtanalysis/pbahaxCy5zy/scaffold5/clean_align.rm4:
2015-03-18 14:50:28,617 [ERROR] Failed cmd with exit code 1 for cmd blasr /nfs/thumper.galaxyproject.org/home/zlf105/Assembly/data/long_filtered_subreads.fasta /nfs/thumper.galaxyproject.org/home/zlf105/Assembly/log/P_AHA/.initial_contigs.fasta -m 4 -minMatch 10 -minPctIdentity 70 -bestn 10 -noSplitSubreads -nproc 16 -out /tmp/smrtanalysis/pbahaxCy5zy/scaffold5/clean_align.rm4.
2015-03-18 14:50:28,618 [ERROR] []
2015-03-18 14:50:28,618 [ERROR] [INFO] 2015-03-18T14:50:28 [blasr] started.
ERROR, FASTA entry must begin with ">"
Process Process-6:
Traceback (most recent call last):
  File "/home/zlf105/lib/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/zlf105/lib/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zlf105/lib/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbaha-0.1.0-py2.7-linux-x86_64.egg/pbaha/main.py", line 507, in wrappedIteration
    outputQueue.put(self._scaffoldIteration(*args))
  File "/home/zlf105/lib/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbaha-0.1.0-py2.7-linux-x86_64.egg/pbaha/main.py", line 608, in _scaffoldIteration
    self._align(readsFasta, cleanContigsFile)
  File "/home/zlf105/lib/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbaha-0.1.0-py2.7-linux-x86_64.egg/pbaha/main.py", line 342, in _align
    backticks(cmd)
  File "/home/zlf105/lib/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbaha-0.1.0-py2.7-linux-x86_64.egg/pbaha/main.py", line 80, in backticks
    raise SubProcessError(stderr)
SubProcessError: [INFO] 2015-03-18T14:50:28 [blasr] started.
ERROR, FASTA entry must begin with ">"
2015-03-18 14:50:28,622 [INFO] Scaffolding failed 
Traceback (most recent call last):
  File "/home/zlf105/lib/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/pbahaScaffolder.py", line 5, in <module>
    pkg_resources.run_script('pbaha==0.1.0', 'pbahaScaffolder.py')
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 489, in run_script
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 1207, in run_script
  File "/nfs/thumper.galaxyproject.org/home/zlf105/lib/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/pbaha-0.1.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pbahaScaffolder.py", line 146, in <module>
    sys.exit(main())
  File "/nfs/thumper.galaxyproject.org/home/zlf105/lib/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/pbaha-0.1.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pbahaScaffolder.py", line 135, in main
    state = aha.run()
  File "/home/zlf105/lib/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbaha-0.1.0-py2.7-linux-x86_64.egg/pbaha/main.py", line 561, in run
    raise Error("Failed to find any links. Scaffolding failed.")
pbaha.main.Error: Failed to find any links. Scaffolding failed.
```
It looks as if either a FASTA file is not being formatted correctly or is not being produced. Is there any guidance for understanding what is going wrong here?

**Comment by pb-jlandolin** [comment]
The error comes from trying to run blasr on these two files:  

/nfs/thumper.galaxyproject.org/home/zlf105/Assembly/data/long_filtered_subreads.fasta /nfs/thumper.galaxyproject.org/home/zlf105/Assembly/log/P_AHA/.initial_contigs.fasta 

You can check if either of these files are correctly formatted.  if long_filtered_subreads.fasta is empty, then you might want to decrease the length cutoff to allow more reads.

If .initial_contigs.fasta is empty or malformed, you should check the reference genome you used for scaffolding.
