### ISSUE TITLE
pbtranscript.py error "TypeError: get_smoothed() takes at least 3 positional arguments (1 given)"

### ISSUE THREAD

**Issue by pengchy** [PacificBiosciences/SMRT-Analysis#190]
Hi,

The command used as listed followed:

source /panfs/home/kang/yangpc/soft/01.NGS_data_process/PacBio/smartanalysis/current/etc/setup.sh
pbtranscript.py cluster /panfs/home/kang/yangpc/Project/09.PacBioRNAseq/02.assem/02.IsoSeq/05.IsoSeq/isoseq_flnc.fasta /panfs/home/kang/yangpc/Project/09.PacBioRNAseq/02.assem/02.IsoSeq/05.IsoSeq/final.consensus.fa --cDNA_size between1k2k

The error message is as following display. could anyone tell me what's wrong?
The isoseq_flnc.fasta file has been split into 11 parts and the blasr for the first part has been done. The error occurred for the second part. If it has successfully run for the first part, why the second failed?

Thank you!
==============================
2015-04-01 01:55:35,880 INFO [main] Multi-threaded. Input: /panfs/home/kang/yangpc/Project/09.PacBioRNAseq/02.assem/02.IsoSeq/05.IsoSeq/run_pbtranscript_cluster.sh.34988.qsub/output/tmp/1/c12565/g_consensus.saln, Threads: 8
[INFO] 2015-04-01T01:55:35 [blasr] started.
[INFO] 2015-04-01T01:55:38 [blasr] ended.
[INFO] 2015-04-01T01:55:38 [blasr] started.
[INFO] 2015-04-01T01:55:39 [blasr] ended.
2015-04-01 01:55:39,150 INFO [main] Multi-threaded. Input: /panfs/home/kang/yangpc/Project/09.PacBioRNAseq/02.assem/02.IsoSeq/05.IsoSeq/run_pbtranscript_cluster.sh.34988.qsub/output/tmp/1/c12566/g_consensus.saln, Threads: 8
2015-04-01 01:56:41,090 [ERROR] Exiting pbtranscript with return code 1.
Traceback (most recent call last):
  File "/panfs/home/kang/yangpc/soft/01.NGS_data_process/PacBio/smartanalysis/current/analysis/bin/pbtranscript.py", line 145, in run
    obj.run()
  File "/panfs/home/kang/yangpc/soft/01.NGS_data_process/PacBio/smartanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/Cluster.py", line 224, in run
    self.icec.run()
  File "/panfs/home/kang/yangpc/soft/01.NGS_data_process/PacBio/smartanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1318, in run
    self.keep_adding_files(sizes=sizes)
  File "/panfs/home/kang/yangpc/soft/01.NGS_data_process/PacBio/smartanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1183, in keep_adding_files
    self.add_new_batch(f)
  File "/panfs/home/kang/yangpc/soft/01.NGS_data_process/PacBio/smartanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1101, in add_new_batch
    self.ensure_probQV_newid_consistency()
  File "/panfs/home/kang/yangpc/soft/01.NGS_data_process/PacBio/smartanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1125, in ensure_probQV_newid_consistency
    self.probQV.get_smoothed(qID=rid, qvname='DeletionQV')
  File "ProbModel.pyx", line 151, in pbtools.pbtranscript.ice.ProbModel.ProbFromModel.get_smoothed (pbtools/pbtranscript/ice/C/ProbModel.cpp:4132)
TypeError: get_smoothed() takes at least 3 positional arguments (1 given)

**Comment by shizhuoxing** [comment]
I also encountered the same problem, has someone to solve now?

**Comment by ylipacbio** [comment]
Thanks for reporting this issue.
I am looking into this issue, will keep you guys posted.

**Comment by ylipacbio** [comment]
Would you please also provide smrtanalysis version number? Thanks

**Comment by shizhuoxing** [comment]
The smrtanalysis is smrtanalysis_2.3.0.140936

**Comment by ylipacbio** [comment]
This bug has been fixed in the latest version on github [pbtranscript tofu](https://github.com/PacificBiosciences/cDNA_primer)  

Two solutions:
(1) Try the following cmd using existing code installed on your system (v2.3):

```pbtranscript.py cluster /panfs/home/kang/yangpc/Project/09.PacBioRNAseq/02.assem/02.IsoSeq/05.IsoSeq/isoseq_flnc.fasta /panfs/home/kang/yangpc/Project/09.PacBioRNAseq/02.assem/02.IsoSeq/05.IsoSeq/final.consensus.fa --cDNA_size between1k2k --ccs_fofn path_to_your_ccs ```

(2) Install latest github version [pbtranscript tofu] (https://github.com/PacificBiosciences/cDNA_primer)

**Comment by shizhuoxing** [comment]
We tested the latest version tofu, it still have error, the code we use as below:
source /path/smrtanalysis/etc/setup.sh
source /paht/VENV_TOFU/bin/activate
/path/VENV_TOFU/bin/pbtranscript.py cluster isoseq_flnc.fasta final.consensus.fa -d cluster --blasr_nproc 24

the error as below:
2016-04-06 16:35:30,003 [ERROR] Exiting pbtranscript with return code 1.
Traceback (most recent call last):
  File "/ifs4/BC_PUB/biosoft/pipeline/RNA/RNA_PacBio/VENV_TOFU/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pbtranscript.py", line 154, in run
    obj.run()
  File "/path/VENV_TOFU/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/Cluster.py", line 225, in run
    ice_fa2fq(firstSplit, self.ccs_fofn, firstSplit_fq)
  File "/path/VENV_TOFU/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/ice/IceUtils.py", line 898, in ice_fa2fq
    if ccs_fofn.endswith(".h5"):  # Input is a ccs.h5 file not a FOFN.
AttributeError: 'NoneType' object has no attribute 'endswith'

it seem need a ccs.h5 file, but we just have a fasta file without ccs.h5, in this case can we use ICE only to get the consensus isoforms? @pengchy report the error is same to me, we just want use ICE without using ccs.h5.

**Comment by uqvirg** [comment]
Hi,
Did you find a solution ? Did you "clean", remove double data ?

I have the same error:
/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1168, in ensure_probQV_newid_consistency
    self.probQV.get_smoothed(qID=rid, qvname='DeletionQV')
  File "ProbModel.pyx", line 237, in pbtools.pbtranscript.ice.ProbModel.ProbFromModel.get_smoothed (pbtools/pbtranscript/ice/C/ProbModel.cpp:5684)
TypeError: get_smoothed() takes at least 3 positional arguments (1 given)


Thank you,
Virginie
