### ISSUE TITLE
ICEclustering fails for large libraries of long reads

### ISSUE THREAD

**Issue by ecaestecker** [PacificBiosciences/SMRT-Analysis#195]
Hi,

I am following the PacBio pipeline described [here](http://github.com)https://github.com/PacificBiosciences/cDNA_primer/wiki/RS_IsoSeq-%28v2.3%29-Tutorial-%232.-Isoform-level-clustering-%28ICE-and-Quiver%29 (thanks for the detailed instructions)

This works fine for my 1-2Kb (standard and normalised) and <1Kb libraries and also for my >6Kb library (which contains a lower number of reads)
**However this fails for my 2-3Kb and 3-6Kb libraries.**

I have tested on a subset of the libraries which are failing, and these run fine up to a certain point, which indicates to me there is a memory issue. However we ran this most recently on a large memory machine, and in its logs the memory usage is nowhere near the available free memory.

**Could you maybe explain what ICE is doing exactly at the ice_pbdagcon step? Is it trying to launch a number of threads which might depend on the number of clusters (and as such indirectly the size of the library?)
How come 680 parallel threads are being used, while specifying a lower number of procs?

This analysis has already been replicated on a different system set-up with identical input without issues, this is why it would be important to understand the internal workings of ICE for us to be able to resolve this on our local systems.

Thanks for any input you could give.
**

version: smrtanalysis-2.3.0.140936

command:
```
pbtranscript.py cluster $path/isoseq_flnc.fasta $path/final.consensus.fa --nfl_fa $path/isoseq_nfl.fasta -d cluster --ccs_fofn $path/reads_of_insert.fofn --bas_fofn $path/input.fofn --cDNA_size above3k --quiver --blasr_nproc 12 --quiver_nproc 12 --hq_quiver_min_accuracy 0.99
```

IceIterative.log
```
DEBUG]  [IceIterative] Initializing IceIterative.
[INFO] [IceIterative] Loading probabilities and QVs from model.
[INFO] [IceIterative] Loading initial clusters from uc.
[INFO] [IceIterative] Creating a reference dict using run_gcon_parallel.
[DEBUG] [IceIterative] use_sge = False
[INFO] [IceIterative] Adding 680 threads for ice_pbdagcon jobs

[DEBUG] [IceIterative] Adding a ice_pbdagcon job thread: ice_pbdagcon.py $path/3-6Kb/cluster/tmp/0/c0/in.fa  $path/3-6Kb/cluster/tmp/0/c0/g_consensus c0 --nproc 8 --maxScore -5000
[DEBUG] [IceIterative] Adding a ice_pbdagcon job thread: ice_pbdagcon.py $path/3-6Kb/cluster/tmp/0/c1/in.fa  $path/3-6Kb/cluster/tmp/0/c1/g_consensus c1 --nproc 8 --maxScore -5000
[DEBUG] [IceIterative] 2015-03-26 09:12:10: [IceIterative] Adding a ice_pbdagcon job thread: ice_pbdagcon.py /gpfs/bayergpfs1/data/run/Projects/DataAnalysis/wheat_pacbio_isoseq/tmp/RS_IsoSeq_cluster/3-6Kb/cluster/tmp/0/c2/in.fa  /gpfs/bayergpfs1/data/run/Projects/DataAnalysis/wheat_pacbio_isoseq/tmp/RS_IsoSeq_cluster/3-6Kb/cluster/tmp/0/c2/g_consensus c2 --nproc 8 --maxScore -5000
...
[DEBUG] [IceIterative] Choosing ref file for 1153 = $path/3-6Kb/cluster/tmp/0/c1153/in.fa.1stseq.fa
[DEBUG] [IceIterative] Picking up the very first sequence as reference.
[DEBUG] [IceIterative] Choosing ref file for 1154 = $path/3-6Kb/cluster/tmp/0/c1154/in.fa.1stseq.fa
[DEBUG] [IceIterative] Picking up the very first sequence as reference.
[DEBUG] [IceIterative] Choosing ref file for 1155 = $path/3-6Kb/cluster/tmp/0/c1155/in.fa.1stseq.fa
...
[DEBUG] [IceIterative] Adding a ice_pbdagcon job thread: ice_pbdagcon.py $path/3-6Kb/cluster/tmp/3/c32754/in.fa  $path/3-6Kb/cluster/tmp/3/c32754/g_consensus c32754 --nproc 8 --maxScore -5000
[DEBUG] [IceIterative] Adding a ice_pbdagcon job thread: ice_pbdagcon.py $path/3-6Kb/cluster/tmp/3/c32762/in.fa  $path/3-6Kb/cluster/tmp/3/c32762/g_consensus c32762 --nproc 8 --maxScore -5000
```

Traceback:
```
2015-04-16 01:45:35,583 [ERROR] Exiting pbtranscript with return code 1.
Traceback (most recent call last):
  File "$path/smrtanalysis-2.3.0.140936/current/analysis/bin/pbtranscript.py", line 145, in run
    obj.run()
  File "$path/smrtanalysis-2.3.0.140936/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/Cluster.py", line 224, in run
    self.icec.run()
  File "$path/smrtanalysis-2.3.0.140936/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1318, in run
    self.keep_adding_files(sizes=sizes)
  File "$path/smrtanalysis-2.3.0.140936/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1186, in keep_adding_files
    self.run_for_new_batch()
  File "$path/smrtanalysis-2.3.0.140936/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1135, in run_for_new_batch
    self.run_til_end(1)
  File "$path/smrtanalysis-2.3.0.140936/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 898, in run_til_end
    self.run_gcon_parallel(self.changes)
  File "$path/smrtanalysis-2.3.0.140936/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 410, in run_gcon_parallel
    self.run_gcon_parallel_helper(cids)
  File "$path/smrtanalysis-2.3.0.140936/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 563, in run_gcon_parallel_helper
    rets = pool.map(runConsensus, jobs)
  File "$path/smrtanalysis-2.3.0.140936/current/redist/python2.7/lib/python2.7/multiprocessing/pool.py", line 227, in map
    return self.map_async(func, iterable, chunksize).get()
  File "$path/smrtanalysis-2.3.0.140936/current/redist/python2.7/lib/python2.7/multiprocessing/pool.py", line 528, in get
    raise self._value
UnboundLocalError: local variable 'ref_filename' referenced before assignment
[INFO] 2015-04-16T01:45:38 [blasr] ended.
[INFO] 2015-04-16T01:45:39 [blasr] ended.
2015-04-16 01:45:39,188 INFO [main] Multi-threaded. Input: $path/3-6Kbcluster/tmp/2/c22074/g_consensus.saln, Threads: 8
[INFO] 2015-04-16T01:45:39 [blasr] started.
[INFO] 2015-04-16T01:45:39 [blasr] ended.
[INFO] 2015-04-16T01:45:40 [blasr] started.
[INFO] 2015-04-16T01:45:40 [blasr] ended.
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '$path/smrtanalysis-2.3.0.140936/current/redist/python2.7/lib/python2.7/threading.pyc'> ignored
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '$path/smrtanalysis-2.3.0.140936/current/redist/python2.7/lib/python2.7/threading.pyc'> ignored
2015-04-16 01:45:56,997 INFO [main] Multi-threaded. Input: $path/3-6Kbcluster/tmp/3/c32650/g_consensus.saln, Threads: 8
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '$path/smrtanalysis-2.3.0.140936/current/redist/python2.7/lib/python2.7/threading.pyc'> ignored
[INFO] 2015-04-16T01:45:57 [blasr] started.
[INFO] 2015-04-16T01:45:57 [blasr] ended.
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '$path/smrtanalysis-2.3.0.140936/current/redist/python2.7/lib/python2.7/threading.pyc'> ignored
2015-04-16 01:45:57,804 INFO [main] Multi-threaded. Input: $path/3-6Kbcluster/tmp/0/c1651/g_consensus.saln, Threads: 8
2015-04-16 01:45:58,213 INFO [main] Multi-threaded. Input: $path/3-6Kbcluster/tmp/2/c22315/g_consensus.saln, Threads: 8
Exception in thread Thread-155 (most likely raised during interpreter shutdown):Exception in thread Thread-162 (most likely raised during interpreter shutdown):Exception in thread Thread-158 (most likely raised during interpreter shutdown):
```

Linux:
Red Hat Enterprise Linux Server release 6.5

**Comment by ylipacbio** [comment]
Hi ecaestecker,

Q: ``Could you maybe explain what ICE is doing exactly at the ice_pbdagcon step? Is it trying to launch a number of threads which might depend on the number of clusters (and as such indirectly the size of the library?)
How come 680 parallel threads are being used, while specifying a lower number of procs?``

A: At ice_pbdagcon step, pbtranscript calls ice_pbdagcon.py in order to build consensus for each isoform cluster. When SGE is not used (i.e., --use_sge not specified, as in your example), only one ice_pbdagcon job will be called at once. Interpreting the log, '680' ice_pbdagcon jobs have been added to the job pool, but only a few jobs will be running at a time. 

This job actually failed because of "UnboundLocalError: local variable 'ref_filename' referenced before assignment". This is a bug reported and fixed by patch S2.3p1 (bug 25888, changelist 141434, 2014/10/20). You can either download the latest patch or leave me your email address, and I can send you updated ice_pbdagcon.py to patch.

Thanks

Sincerely,
Yuan

**Comment by ecaestecker** [comment]
Thanks for your repsons, I thought we had installed the patch also, but I will double check this and leave a comment here when resolved.
