### ISSUE TITLE
HGAP3 Assembly Fails: hgapFilterM4 TypeError: Expected 13 arguments got 25

### ISSUE THREAD

**Issue by lparsons** [PacificBiosciences/SMRT-Analysis#199]
When running an HGAP 3 job I get the following error in the `P_PreAssemblerDagcon/hgapFilterM4` module. This occurs with SMRTPortal generated settings.xml as well as custom ones.  Running `smrtanalysis_2.3.0.140936`

    [DEBUG] 2015-05-04 16:13:23,910 [SMRTpipe.engine.SmrtPipeTasks run 702] Task hgapFilterM4_004of006 looking for errors in log /Genomics/grid/users/lparsons/bnazari/pacbio_test/output_hgap3/log/P_PreAssemblerDagcon/hgapFilterM4_004of006.log
    [ERROR] 2015-05-04 16:13:23,911 [SMRTpipe.engine.SmrtPipeTasks run 706] > Setting up ENV on cetus-c1-01.gen.pvt for task hgapFilterM4_004of006
    [ERROR] 2015-05-04 16:13:23,911 [SMRTpipe.engine.SmrtPipeTasks run 706] > Running task://Anonymous/P_PreAssemblerDagcon/hgapFilterM4_004of006 on Linux cetus-c1-01.gen.pvt 2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 20:53:06 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
    [ERROR] 2015-05-04 16:13:23,911 [SMRTpipe.engine.SmrtPipeTasks run 706] > Started on Mon May  4 20:13:23 UTC 2015
    [ERROR] 2015-05-04 16:13:23,911 [SMRTpipe.engine.SmrtPipeTasks run 706] > Validating existence of Input Files
    [ERROR] 2015-05-04 16:13:23,912 [SMRTpipe.engine.SmrtPipeTasks run 706] > Successfully found /Genomics/grid/users/lparsons/bnazari/pacbio_test/output_hgap3/seeds.chunk004of006.m4
    [ERROR] 2015-05-04 16:13:23,912 [SMRTpipe.engine.SmrtPipeTasks run 706] > Successfully validated input files
    [ERROR] 2015-05-04 16:13:23,912 [SMRTpipe.engine.SmrtPipeTasks run 706] > Task 1 completed at Mon May  4 16:13:23 EDT 2015
    [ERROR] 2015-05-04 16:13:23,912 [SMRTpipe.engine.SmrtPipeTasks run 706] > Traceback (most recent call last):
    [ERROR] 2015-05-04 16:13:23,912 [SMRTpipe.engine.SmrtPipeTasks run 706] > File "/usr/local/smrt/current/analysis/bin/filterm4.py", line 64, in <module>
    [ERROR] 2015-05-04 16:13:23,912 [SMRTpipe.engine.SmrtPipeTasks run 706] > sys.exit(main())
    [ERROR] 2015-05-04 16:13:23,913 [SMRTpipe.engine.SmrtPipeTasks run 706] > File "/usr/local/smrt/current/analysis/bin/filterm4.py", line 52, in main
    [ERROR] 2015-05-04 16:13:23,913 [SMRTpipe.engine.SmrtPipeTasks run 706] > m = M4Record._make(rec.split())
    [ERROR] 2015-05-04 16:13:23,913 [SMRTpipe.engine.SmrtPipeTasks run 706] > File "<string>", line 17, in _make
    [ERROR] 2015-05-04 16:13:23,913 [SMRTpipe.engine.SmrtPipeTasks run 706] > TypeError: Expected 13 arguments, got 25
    [ERROR] 2015-05-04 16:13:23,913 [SMRTpipe.engine.SmrtPipeTasks run 706] > ## TASK metadata #############
    [ERROR] 2015-05-04 16:13:23,913 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Task            : hgapFilterM4_004of006
    [ERROR] 2015-05-04 16:13:23,914 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Module          : P_PreAssemblerDagcon
    [ERROR] 2015-05-04 16:13:23,914 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Module Version  : 2.1.124285
    [ERROR] 2015-05-04 16:13:23,914 [SMRTpipe.engine.SmrtPipeTasks run 706] > # TaskType        : None
    [ERROR] 2015-05-04 16:13:23,914 [SMRTpipe.engine.SmrtPipeTasks run 706] > # URL             : task://Anonymous/P_PreAssemblerDagcon/hgapFilterM4_004of006
    [ERROR] 2015-05-04 16:13:23,914 [SMRTpipe.engine.SmrtPipeTasks run 706] > # createdAt       : 2015-05-04 15:53:57.510796
    [ERROR] 2015-05-04 16:13:23,915 [SMRTpipe.engine.SmrtPipeTasks run 706] > # createdAt (UTC) : 2015-05-04 19:53:57.510824
    [ERROR] 2015-05-04 16:13:23,915 [SMRTpipe.engine.SmrtPipeTasks run 706] > # ncmds           : 5
    [ERROR] 2015-05-04 16:13:23,915 [SMRTpipe.engine.SmrtPipeTasks run 706] > # LogPath         : /Genomics/grid/users/lparsons/bnazari/pacbio_test/output_hgap3/log/P_PreAssemblerDagcon/hgapFilterM4_004of006.log
    [ERROR] 2015-05-04 16:13:23,915 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Script Path     : /Genomics/grid/users/lparsons/bnazari/pacbio_test/output_hgap3/workflow/P_PreAssemblerDagcon/hgapFilterM4_004of006.sh
    [ERROR] 2015-05-04 16:13:23,915 [SMRTpipe.engine.SmrtPipeTasks run 706] >
    [ERROR] 2015-05-04 16:13:23,915 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Input       : /Genomics/grid/users/lparsons/bnazari/pacbio_test/output_hgap3/seeds.chunk004of006.m4
    [ERROR] 2015-05-04 16:13:23,916 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Output      : /Genomics/grid/users/lparsons/bnazari/pacbio_test/output_hgap3/.chunk004of006.seeds.m4.filter
    [ERROR] 2015-05-04 16:13:23,916 [SMRTpipe.engine.SmrtPipeTasks run 706] > #
    [ERROR] 2015-05-04 16:13:23,916 [SMRTpipe.engine.SmrtPipeTasks run 706] > ########### END TASK metadata #############
    [ERROR] 2015-05-04 16:13:23,916 [SMRTpipe.engine.SmrtPipeTasks run 706] >

**Comment by lparsons** [comment]
Long story short, this has been resolved by fixing our template scripts for SLURM (see https://github.com/PacificBiosciences/SMRT-Analysis/issues/78#issuecomment-101755973).
