### ISSUE TITLE
Lambda test run failing with 

### ISSUE THREAD

**Issue by el-mat** [PacificBiosciences/SMRT-Analysis#207]
I have performed a Lambda test assembly in a SMRT-Analysis virtual machine according to the instructions found at  https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/SMRT-Analysis-Virtual-Machine-Install.

The de novo assembly (RS_HGAP_Assembly.2, genome size set at 40,000) fails with the following log message:
Exiting smrtpipe last error: SmrtExit task://016443/P_CeleraAssembler/runCaHgap Failed

This is the first ERROR message I found in the error log. The whole log was way to large to paste!

[ERROR] 2015-05-28 14:08:01,326 [SMRTpipe.engine.SmrtPipeTasks _run_task 773] task://016443/P_CeleraAssembler/runCaHgap returned non-zero exit status (1)
[DEBUG] 2015-05-28 14:08:01,327 [SMRTpipe.engine.SmrtPipeTasks run 694] Adding Failed Task task://016443/P_CeleraAssembler/runCaHgap to the queue
[ERROR] 2015-05-28 14:08:01,327 [SMRTpipe.engine.SmrtPipeTasks run 695] task://016443/P_CeleraAssembler/runCaHgap returned non-zero exit status (1)
Traceback (most recent call last):
  File "/home/vagrant/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeTasks.py", line 689, in run
    self._run_task(*args, **kwargs)
  File "/home/vagrant/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeTasks.py", line 774, in _run_task
    raise TaskExecutionError(msg)
TaskExecutionError: task://016443/P_CeleraAssembler/runCaHgap returned non-zero exit status (1)
[ERROR] 2015-05-28 14:08:01,327 [SMRTpipe.engine.SmrtPipeTasks run 696] task://016443/P_CeleraAssembler/runCaHgap returned non-zero exit status (1)
Traceback (most recent call last):
  File "/home/vagrant/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeTasks.py", line 689, in run
    self._run_task(*args, **kwargs)
  File "/home/vagrant/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeTasks.py", line 774, in _run_task
    raise TaskExecutionError(msg)
TaskExecutionError: task://016443/P_CeleraAssembler/runCaHgap returned non-zero exit status (1)
[ERROR] 2015-05-28 14:08:01,327 [SMRTpipe.engine.SmrtPipeTasks run 698] Traceback (most recent call last):
  File "/home/vagrant/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeTasks.py", line 689, in run
    self._run_task(*args, **kwargs)
  File "/home/vagrant/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeTasks.py", line 774, in _run_task
    raise TaskExecutionError(msg)
TaskExecutionError: task://016443/P_CeleraAssembler/runCaHgap returned non-zero exit status (1)
Traceback (most recent call last):
  File "/home/vagrant/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeTasks.py", line 689, in run
    self._run_task(*args, **kwargs)
  File "/home/vagrant/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeTasks.py", line 774, in _run_task
    raise TaskExecutionError(msg)
TaskExecutionError: task://016443/P_CeleraAssembler/runCaHgap returned non-zero exit status (1)
[DEBUG] 2015-05-28 14:08:01,328 [SMRTpipe.engine.SmrtPipeTasks run 702] Task runCaHgap looking for errors in log /home/vagrant/userdata/jobs/016/016443/log/P_CeleraAssembler/runCaHgap.log
[ERROR] 2015-05-28 14:08:01,328 [SMRTpipe.engine.SmrtPipeTasks run 706] > #!/bin/bash
[ERROR] 2015-05-28 14:08:01,328 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Setting up SMRTpipe environment
[ERROR] 2015-05-28 14:08:01,328 [SMRTpipe.engine.SmrtPipeTasks run 706] > echo "Setting up ENV on $(uname -n)" for task runCaHgap
[ERROR] 2015-05-28 14:08:01,328 [SMRTpipe.engine.SmrtPipeTasks run 706] > 
[ERROR] 2015-05-28 14:08:01,328 [SMRTpipe.engine.SmrtPipeTasks run 706] > SEYMOUR_HOME=/home/vagrant/install/smrtanalysis_2.3.0.140936
[ERROR] 2015-05-28 14:08:01,328 [SMRTpipe.engine.SmrtPipeTasks run 706] > source $SEYMOUR_HOME/etc/setup.sh
[ERROR] 2015-05-28 14:08:01,328 [SMRTpipe.engine.SmrtPipeTasks run 706] > 
[ERROR] 2015-05-28 14:08:01,328 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Create the local TMP dir if it doesn't exist
[ERROR] 2015-05-28 14:08:01,328 [SMRTpipe.engine.SmrtPipeTasks run 706] > tmp_dir=$(readlink -m "/home/vagrant/tmpdir")
[ERROR] 2015-05-28 14:08:01,328 [SMRTpipe.engine.SmrtPipeTasks run 706] > if [ ! -e "$tmp_dir" ]; then
[ERROR] 2015-05-28 14:08:01,328 [SMRTpipe.engine.SmrtPipeTasks run 706] > stat=0
[ERROR] 2015-05-28 14:08:01,329 [SMRTpipe.engine.SmrtPipeTasks run 706] > mkdir -p $tmp_dir || stat=$?
[ERROR] 2015-05-28 14:08:01,329 [SMRTpipe.engine.SmrtPipeTasks run 706] > if [[ $stat -ne 0 ]]; then
[ERROR] 2015-05-28 14:08:01,329 [SMRTpipe.engine.SmrtPipeTasks run 706] > echo "SMRTpipe Unable to create TMP dir '/home/vagrant/tmpdir' on $(uname -n)" 1>&2
[ERROR] 2015-05-28 14:08:01,329 [SMRTpipe.engine.SmrtPipeTasks run 706] > exit 1
[ERROR] 2015-05-28 14:08:01,329 [SMRTpipe.engine.SmrtPipeTasks run 706] > else
[ERROR] 2015-05-28 14:08:01,329 [SMRTpipe.engine.SmrtPipeTasks run 706] > echo "successfully created or found TMP dir '/home/vagrant/tmpdir'"
[ERROR] 2015-05-28 14:08:01,329 [SMRTpipe.engine.SmrtPipeTasks run 706] > fi
[ERROR] 2015-05-28 14:08:01,329 [SMRTpipe.engine.SmrtPipeTasks run 706] > elif [[ ! -d "$tmp_dir" ]]; then
[ERROR] 2015-05-28 14:08:01,329 [SMRTpipe.engine.SmrtPipeTasks run 706] > echo "SMRTpipe TMP /home/vagrant/tmpdir must be a directory on $(uname -n)" 1>&2
[ERROR] 2015-05-28 14:08:01,329 [SMRTpipe.engine.SmrtPipeTasks run 706] > exit 1
[ERROR] 2015-05-28 14:08:01,329 [SMRTpipe.engine.SmrtPipeTasks run 706] > fi
[ERROR] 2015-05-28 14:08:01,329 [SMRTpipe.engine.SmrtPipeTasks run 706] > 
[ERROR] 2015-05-28 14:08:01,330 [SMRTpipe.engine.SmrtPipeTasks run 706] > ########### TASK metadata #############
[ERROR] 2015-05-28 14:08:01,330 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Task            : runCaHgap
[ERROR] 2015-05-28 14:08:01,330 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Module          : P_CeleraAssembler
[ERROR] 2015-05-28 14:08:01,330 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Module Version  : 2.1.139483
[ERROR] 2015-05-28 14:08:01,330 [SMRTpipe.engine.SmrtPipeTasks run 706] > # TaskType        : None
[ERROR] 2015-05-28 14:08:01,330 [SMRTpipe.engine.SmrtPipeTasks run 706] > # URL             : task://016443/P_CeleraAssembler/runCaHgap
[ERROR] 2015-05-28 14:08:01,330 [SMRTpipe.engine.SmrtPipeTasks run 706] > # createdAt       : 2015-05-28 13:44:35.812391
[ERROR] 2015-05-28 14:08:01,330 [SMRTpipe.engine.SmrtPipeTasks run 706] > # createdAt (UTC) : 2015-05-28 13:44:35.812439
[ERROR] 2015-05-28 14:08:01,330 [SMRTpipe.engine.SmrtPipeTasks run 706] > # ncmds           : 5
[ERROR] 2015-05-28 14:08:01,330 [SMRTpipe.engine.SmrtPipeTasks run 706] > # LogPath         : /home/vagrant/userdata/jobs/016/016443/log/P_CeleraAssembler/runCaHgap.log
[ERROR] 2015-05-28 14:08:01,330 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Script Path     : /home/vagrant/userdata/jobs/016/016443/workflow/P_CeleraAssembler/runCaHgap.sh
[ERROR] 2015-05-28 14:08:01,330 [SMRTpipe.engine.SmrtPipeTasks run 706] > 
[ERROR] 2015-05-28 14:08:01,330 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Input       : /home/vagrant/userdata/jobs/016/016443/data/corrected.frg
[ERROR] 2015-05-28 14:08:01,331 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Input       : /home/vagrant/userdata/jobs/016/016443/data/runCA.spec
[ERROR] 2015-05-28 14:08:01,331 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Output      : /home/vagrant/userdata/jobs/016/016443/data/celera-assembler.singleton.fasta
[ERROR] 2015-05-28 14:08:01,331 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Output      : /home/vagrant/userdata/jobs/016/016443/data/celera-assembler.scf.fasta
[ERROR] 2015-05-28 14:08:01,331 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Output      : /home/vagrant/userdata/jobs/016/016443/data/celera-assembler.asm
[ERROR] 2015-05-28 14:08:01,331 [SMRTpipe.engine.SmrtPipeTasks run 706] > # Output      : /home/vagrant/userdata/jobs/016/016443/data/celera-assembler.deg.fasta

**Comment by jkaralius** [comment]
Hi @el-mat 

Please post the contents of the following log file into a [public gist] (https://gist.github.com/), and post the link here:
`/home/vagrant/userdata/jobs/016/016443/log/P_CeleraAssembler/runCaHgap.log`

**Comment by el-mat** [comment]
Dear jkaralius,
Thank you for your answer.
You can find the content of the runCaHgap.log here:
https://gist.github.com/bfb1b09b6693a976200e.git
