### ISSUE TITLE
SmrtExit task://Anonymous/P_Filter/filter_002of003 Failed

### ISSUE THREAD

**Issue by Malabady** [PacificBiosciences/SMRT-Analysis#209]
[INFO] 2015-06-02 05:41:47,222 [smrtpipe.status refreshTargets 407] task P_Fetch.toFofn successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 0 slots.
[INFO] 2015-06-02 05:41:47,222 [smrtpipe.status refreshTargets 409] Workflow Completion Status 1/44 in (            2%) tasks completed.
[INFO] 2015-06-02 05:41:52,230 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Fetch/adapterRpt
[INFO] 2015-06-02 05:41:52,230 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Fetch/overviewRpt
[INFO] 2015-06-02 05:41:52,230 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/subreads.plsFofn.Scatter
[INFO] 2015-06-02 05:41:52,233 [smrtpipe.status refreshTargets 407] task P_Filter.subreads.plsFofn.Scatter successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 2 slots.
[INFO] 2015-06-02 05:41:52,233 [smrtpipe.status refreshTargets 409] Workflow Completion Status 2/44 in (            4%) tasks completed.
[INFO] 2015-06-02 05:41:56,137 [smrtpipe.status refreshTargets 407] task P_Fetch.overviewRpt successfully completed (4.00 sec (0.07 min)). freed 1 slots, using 1 slots.
[INFO] 2015-06-02 05:41:56,139 [smrtpipe.status refreshTargets 409] Workflow Completion Status 3/44 in (            6%) tasks completed.
[INFO] 2015-06-02 05:42:01,206 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/filter_002of003
[INFO] 2015-06-02 05:42:01,207 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/filter_001of003
[INFO] 2015-06-02 05:42:01,207 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/filter_003of003
[INFO] 2015-06-02 05:42:51,204 [smrtpipe.status refreshTargets 407] task P_Fetch.adapterRpt successfully completed (56.00 sec (0.93 min)). freed 1 slots, using 6 slots.
[INFO] 2015-06-02 05:42:51,204 [smrtpipe.status refreshTargets 409] Workflow Completion Status 4/44 in (            9%) tasks completed.
[INFO] 2015-06-02 05:42:51,206 [smrtpipe.status refreshTargets 407] task P_Filter.filter_001of003 successfully completed (49.00 sec (0.82 min)). freed 2 slots, using 4 slots.
[INFO] 2015-06-02 05:42:51,206 [smrtpipe.status refreshTargets 409] Workflow Completion Status 5/44 in (         . 11%) tasks completed.
[INFO] 2015-06-02 05:42:51,208 [smrtpipe.status refreshTargets 407] task P_Filter.filter_003of003 successfully completed (49.00 sec (0.82 min)). freed 2 slots, using 2 slots.
[INFO] 2015-06-02 05:42:51,208 [smrtpipe.status refreshTargets 409] Workflow Completion Status 6/44 in (         . 13%) tasks completed.
[ERROR] 2015-06-02 05:42:51,208 [smrtpipe.status refreshTargets 413] *** Failed task task://Anonymous/P_Filter/filter_002of003
[INFO] 2015-06-02 05:42:51,209 [smrtpipe.status execute 627] Found 1 failed tasks.
[INFO] 2015-06-02 05:42:51,209 [smrtpipe.status execute 629] task filter_002of003 FAILED 
[ERROR] 2015-06-02 05:42:52,301 [SMRTpipe.SmrtPipeMain run 608] SmrtExit task://Anonymous/P_Filter/filter_002of003 Failed
Traceback (most recent call last):
  File "/usr/local/smrtanalysis/latest/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 571, in run
    self._runTasks(pModules)
  Hi, 

I am running SMARtanalysis (V2.3) and I getting the following error. Assuming the error has something to do with the data files of this cell, I tried the analysis with other cells but still getting the same error. 

Any suggestion on solving this error will be appreciated. 

Thanks
Magdy
=============================================================

File "/usr/local/smrtanalysis/latest/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 300, in _runTasks
    workflow.execute()
  File "/usr/local/smrtanalysis/latest/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeWorkflow.py", line 640, in execute
    raise SmrtExit(str(e))
SmrtExit: SmrtExit task://Anonymous/P_Filter/filter_002of003 Failed
[ERROR] 2015-06-02 05:42:52,302 [SMRTpipe.SmrtPipeMain exit 690] SmrtExit task://Anonymous/P_Filter/filter_002of003 Failed
[INFO] 2015-06-02 05:42:52,302 [SMRTpipe.SmrtPipeMain exit 692] Beginning exit process
[INFO] 2015-06-02 05:42:52,302 [SMRTpipe.SmrtPipeMain shutdown 716] beginning Shutdown Process
[INFO] 2015-06-02 05:42:52,302 [SMRTpipe.SmrtPipeMain _generate_final_report 651] Writing final TOC page with error message : SmrtExit task://Anonymous/P_Filter/filter_002of003 Failed
[INFO] 2015-06-02 05:42:53,826 [SMRTpipe.SmrtPipeMain shutdown 752] Completed shutdown gracefully
[INFO] 2015-06-02 05:42:53,826 [SMRTpipe.SmrtPipeMain exit 702] Sending message Exiting smrtpipe last error: SmrtExit task://Anonymous/P_Filter/filter_002of003 Failed
[INFO] 2015-06-02 05:42:53,844 [SMRTpipe.SmrtPipeMain run 641] completed SmrtPipeMain.run with exit code -1
[INFO] 2015-06-02 05:42:53,844 [root main 335] Failed smrtpipe version v1.87.139483 with exit code -1 in 80.81 seconds (1.35 minutes)

**Comment by mjhsieh** [comment]
It would be nice if you can provide the log at log/P_Filter/filter_002of003.log , please use &lt;pre&gt;&lt;/pre&gt; to quote the content or use gist for log sharing.

**Comment by nahlgren** [comment]
I'm getting a similar issue.
Was this issue resolved?
I'm fairly new to github. What other info can I provide?

From log window in SMRT Portal:

[ERROR] 2015-09-03 16:08:35,597 [SMRTpipe.SmrtPipeMain exit 690] SmrtExit task://016442/P_Filter/subreads_004of006 Failed
[INFO] 2015-09-03 16:08:35,597 [SMRTpipe.SmrtPipeMain exit 692] Beginning exit process
[INFO] 2015-09-03 16:08:35,597 [SMRTpipe.SmrtPipeMain shutdown 716] beginning Shutdown Process
[INFO] 2015-09-03 16:08:35,598 [SMRTpipe.SmrtPipeMain _generate_final_report 651] Writing final TOC page with error message : SmrtExit task://016442/P_Filter/subreads_004of006 Failed
[INFO] 2015-09-03 16:08:57,616 [SMRTpipe.SmrtPipeMain shutdown 752] Completed shutdown gracefully
[INFO] 2015-09-03 16:08:57,617 [SMRTpipe.SmrtPipeMain exit 702] Sending message Exiting smrtpipe last error: SmrtExit task://016442/P_Filter/subreads_004of006 Failed
[INFO] 2015-09-03 16:08:57,617 [smrtpipe.status failed 104] Sending Job 016442 failed message 'Exiting smrtpipe last error: SmrtExit task://016442/P_Filter/subreads_004of006 Failed' to url http://kraken.usc.edu:9999/smrtportal/api/jobs/016442/status
[INFO] 2015-09-03 16:08:57,700 [SMRTpipe.SmrtPipeMain run 641] completed SmrtPipeMain.run with exit code -1
[INFO] 2015-09-03 16:08:57,700 [root main 335] Failed smrtpipe version v1.87.139483 with exit code -1 in 412.58 seconds (6.88 minutes)
