### ISSUE TITLE
Can't open object

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/SMRT-Analysis#222]
Hi there,

I tried to use cmpH5Merge to merge some `cmp.h5` files and always failed with the following error. Could you tell me how to troubleshoot? Thanks.

```
Traceback (most recent call last):
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/cmph5tools.py", line 240, in <module>
    sys.exit(CmpH5ToolsRunner().start())
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbcore/util/ToolRunner.py", line 105, in start
    return self.run()
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/cmph5tools.py", line 182, in run
    cmpH5Merge(self.args.inCmps, self.args.outCmp, self.args.referencesFile)
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbh5tools/CmpH5Merge.py", line 310, in cmpH5Merge
    uRefsWithAlignments = NP.unique(outCmp[fmt.ALN_INDEX][:,fmt.REF_ID])
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:2946)
KeyError: "unable to open object (Symbol table: Can't open object)"
```

**Comment by mjhsieh** [comment]
If you are sure the cmp.h5 files are all okay, it might be the case that you are merging files where they might be product of mapping against different references.

**Comment by yunfeiguo** [comment]
Hi Mengjuei,

The files all use the same reference. Do you know how to identify the
problematic cmp.h5 file?

**Comment by yunfeiguo** [comment]
I have two `cmp.h5` files for reproducing the error. The version of smrt-analysis is `2.3.0.140936`. Thanks.

The commands I used are
```
source `/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/admin/bin/getsetupfile`
export PATH=$PATH:/opt/openmpi/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/eclipse:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/java/latest/bin:/opt/maven/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/opt/gridengine/bin/linux-x64
declare -x PDSHROOT="/opt/pdsh"
declare -x PRODUCTNMAME
declare -x QTDIR="/usr/lib64/qt-3.3"
declare -x QTINC="/usr/lib64/qt-3.3/include"
declare -x QTLIB="/usr/lib64/qt-3.3/lib"
declare -x ROCKSROOT="/opt/rocks/share/devel"
declare -x ROCKS_ROOT="/opt/rocks"
declare -x ROLLSROOT="/opt/rocks/share/devel/src/roll"
declare -x SGE_ARCH="linux-x64"
declare -x SGE_CELL="default"
declare -x SGE_EXECD_PORT="537"
declare -x SGE_QMASTER_PORT="536"
declare -x SGE_ROOT="/opt/gridengine"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"

cmph5tools.py merge --referencesFile ref.fa --outFile merge.cmp.h5 1.cmp.h5 2.cmp.h5
```

http://bionas.usc.edu:5000/fbsharing/Jt2mviOH
http://bionas.usc.edu:5000/fbsharing/lWlX42f3

**Comment by mjhsieh** [comment]
Hi, I was able to merge 1/2.cmp.h5 without the ref.fa perhaps the reference wasn't correct.
```
# first the reference info in cmp.h5 looks the same
$ h5dump -d /RefInfo/MD5 1.cmp.h5 > 1.RefInfo_MD5
$ h5dump -d /RefInfo/MD5 2.cmp.h5 > 2.RefInfo_MD5
$ diff -u 1.RefInfo_MD5 2.RefInfo_MD5
--- 1.RefInfo_MD5       2015-09-06 21:21:05.000000000 -0700
+++ 2.RefInfo_MD5       2015-09-06 21:21:14.000000000 -0700
@@ -1,4 +1,4 @@
-HDF5 "1.cmp.h5" {
+HDF5 "2.cmp.h5" {
 DATASET "/RefInfo/MD5" {
    DATATYPE  H5T_STRING {
       STRSIZE H5T_VARIABLE;
# secondly test the merge
$ /smrtportal/smrtcmds/bin/smrtwrap cmph5tools.py merge --outFile merged.cmp.h5 1.cmp.h5 2.cmp.h5 
$ echo $?
0
```

**Comment by yunfeiguo** [comment]
Hi Mengjuei,

Your commands worked. Thank you!

I wonder what is difference between running smrtwrap and "source
smrtanalysis/install/smrtanalysis_2.3.0.140936/admin/bin/getsetupfile"?
Apparently the later did not do the right thing.
