### ISSUE TITLE
HGAP_Assembly.3 fails

### ISSUE THREAD

**Issue by gedankenstuecke** [PacificBiosciences/SMRT-Analysis#223]
Hi there,
I'm having the problem that HGAP fails when doing an assembly with ~18 SMRTs at the P_PreAssemblerDagcon step with an error (see below), but somehow I'm not clever enough to figure out where to learn more about it and how to fix it. Where should I look for more details on this? :-)

Cheers,
Bastian

```

INFO] 2015-09-08 10:41:22,441 [SMRTpipe.SmrtPipeMain _getBasVersions 413] Detected basH5 versions set(['-v2.3.0'])
[INFO] 2015-09-08 10:41:23,062 [smrtpipe.status run 503] smrtpipe.py running on sheldon
[INFO] 2015-09-08 10:41:23,063 [SMRTpipe.SmrtPipeMain run 506] using Distributed mode with 2 nproc
[INFO] 2015-09-08 10:41:23,063 [smrtpipe.status run 519] SMRT Analysis 2.3.0 / SMRTpipe 1.87.139483
[INFO] 2015-09-08 10:41:23,063 [SMRTpipe.SmrtPipeMain run 522] Starting smrtpipe version 1.87.139483
[INFO] 2015-09-08 10:41:23,645 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_Fetch module
[INFO] 2015-09-08 10:41:23,651 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_Fetch v2.4.139483 and validated settings.
[INFO] 2015-09-08 10:41:23,661 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_Filter module
[INFO] 2015-09-08 10:41:23,664 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_Filter v1.7.139483 and validated settings.
[INFO] 2015-09-08 10:41:23,666 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_FilterReports module
[INFO] 2015-09-08 10:41:23,666 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_FilterReports v1.21.139483 and validated settings.
[INFO] 2015-09-08 10:41:23,674 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_PreAssemblerDagcon module
[INFO] 2015-09-08 10:41:23,676 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_PreAssemblerDagcon v2.1.124285 and validated settings.
[INFO] 2015-09-08 10:41:23,680 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_AssembleUnitig module
[INFO] 2015-09-08 10:41:23,682 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_AssembleUnitig v2.2.UnknownVersion and validated settings.
[INFO] 2015-09-08 10:41:23,693 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_ReferenceUploader module
[INFO] 2015-09-08 10:41:23,695 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_ReferenceUploader v1.2.139483 and validated settings.
[INFO] 2015-09-08 10:41:23,700 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_Mapping module
[INFO] 2015-09-08 10:41:23,705 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_Mapping v1.33.141997 and validated settings.
[INFO] 2015-09-08 10:41:23,720 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_MappingReports module
[INFO] 2015-09-08 10:41:23,720 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_MappingReports v1.7.140023 and validated settings.
[INFO] 2015-09-08 10:41:23,723 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_AssemblyPolishing module
[INFO] 2015-09-08 10:41:23,725 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_AssemblyPolishing v1.36.139483 and validated settings.
[INFO] 2015-09-08 10:41:23,727 [SMRTpipe.SmrtDataService writeTo 424] Writing 6 items to DataStore in {'smrt.data.xmlparam': <InputDataUrl ref:/home/bastian/bin/smrtanalysis/userdata/jobs/016/016449/settings.xml >, 'smrt.output.log': '/home/bastian/bin/smrtanalysis/userdata/jobs/016/016449/log', 'smrt.data.cmdline': <CompositeInputData url:xml:/home/bastian/bin/smrtanalysis/userdata/jobs/016/016449/input.xml job:<JobInfo id:016449 name:assemble fast > >, 'smrt.output.root': '/home/bastian/bin/smrtanalysis/userdata/jobs/016/016449', 'smrt.output.results': '/home/bastian/bin/smrtanalysis/userdata/jobs/016/016449/results', 'smrt.output.data': '/home/bastian/bin/smrtanalysis/userdata/jobs/016/016449/data'}
[INFO] 2015-09-08 10:41:23,733 [SMRTpipe.SmrtPipeMain _runTasks 281] Skipping PreWorkflow as it contains zero tasks
[INFO] 2015-09-08 10:41:23,736 [SMRTpipe.SmrtPipeMain _runTasks 284] Loading 35 tasks into Workflow
[INFO] 2015-09-08 10:41:25,074 [SMRTpipe.SmrtPipeMain _runTasks 298] Executing workflow Workflow
[INFO] 2015-09-08 10:41:25,075 [smrtpipe.status execute 620] Process id 4362
[INFO] 2015-09-08 10:41:31,294 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Fetch/toFofn
[INFO] 2015-09-08 10:41:31,318 [smrtpipe.status refreshTargets 407] task P_Fetch.toFofn successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 0 slots.
[INFO] 2015-09-08 10:41:31,318 [smrtpipe.status refreshTargets 409] Workflow Completion Status 1/56 in (            1%) tasks completed.
[INFO] 2015-09-08 10:41:36,328 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Mapping/align.plsFofn.Scatter
[INFO] 2015-09-08 10:41:36,328 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Fetch/adapterRpt
[INFO] 2015-09-08 10:41:36,356 [smrtpipe.status refreshTargets 407] task P_Mapping.align.plsFofn.Scatter successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 1 slots.
[INFO] 2015-09-08 10:41:36,356 [smrtpipe.status refreshTargets 409] Workflow Completion Status 2/56 in (            3%) tasks completed.
[INFO] 2015-09-08 11:03:22,901 [smrtpipe.status refreshTargets 407] task P_Fetch.adapterRpt successfully completed (1050.00 sec (17.50 min)). freed 1 slots, using 0 slots.
[INFO] 2015-09-08 11:03:22,929 [smrtpipe.status refreshTargets 409] Workflow Completion Status 3/56 in (            5%) tasks completed.
[INFO] 2015-09-08 11:03:27,962 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Filter/filter_001of002
[INFO] 2015-09-08 11:48:03,264 [smrtpipe.status refreshTargets 407] task P_Filter.filter_001of002 successfully completed (2053.00 sec (34.22 min)). freed 2 slots, using 0 slots.
[INFO] 2015-09-08 11:48:03,264 [smrtpipe.status refreshTargets 409] Workflow Completion Status 4/56 in (            7%) tasks completed.
[INFO] 2015-09-08 11:48:08,271 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Filter/subreads_001of002
[INFO] 2015-09-08 17:20:47,850 [smrtpipe.status refreshTargets 407] task P_Filter.subreads_001of002 successfully completed (4717.00 sec (78.62 min)). freed 1 slots, using 0 slots.
[INFO] 2015-09-08 17:20:47,851 [smrtpipe.status refreshTargets 409] Workflow Completion Status 5/56 in (            8%) tasks completed.
[INFO] 2015-09-08 17:20:52,947 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Filter/filter_002of002
[INFO] 2015-09-08 17:38:47,878 [smrtpipe.status refreshTargets 407] task P_Filter.filter_002of002 successfully completed (1073.00 sec (17.88 min)). freed 2 slots, using 0 slots.
[INFO] 2015-09-08 17:38:47,878 [smrtpipe.status refreshTargets 409] Workflow Completion Status 6/56 in (         . 10%) tasks completed.
[INFO] 2015-09-08 17:38:53,745 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Filter/filter.rgnFofn.Gather
[INFO] 2015-09-08 17:38:53,745 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Filter/subreads_002of002
[INFO] 2015-09-08 17:38:53,762 [smrtpipe.status refreshTargets 407] task P_Filter.filter.rgnFofn.Gather successfully completed (1.00 sec (0.02 min)). freed 1 slots, using 1 slots.
[INFO] 2015-09-08 17:38:53,762 [smrtpipe.status refreshTargets 409] Workflow Completion Status 7/56 in (         . 12%) tasks completed.
[INFO] 2015-09-08 17:38:58,769 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Filter/subreadSummary
[INFO] 2015-09-08 18:01:26,408 [smrtpipe.status refreshTargets 407] task P_Filter.subreadSummary successfully completed (1341.00 sec (22.35 min)). freed 1 slots, using 1 slots.
[INFO] 2015-09-08 18:01:26,409 [smrtpipe.status refreshTargets 409] Workflow Completion Status 8/56 in (         . 14%) tasks completed.
[INFO] 2015-09-08 18:01:31,415 [smrtpipe.status refreshTargets 419] Starting task://016449/P_FilterReports/subreadRpt
[INFO] 2015-09-08 18:02:53,520 [smrtpipe.status refreshTargets 407] task P_FilterReports.subreadRpt successfully completed (78.00 sec (1.30 min)). freed 1 slots, using 1 slots.
[INFO] 2015-09-08 18:02:53,520 [smrtpipe.status refreshTargets 409] Workflow Completion Status 9/56 in (         . 16%) tasks completed.
[INFO] 2015-09-08 18:02:58,618 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Filter/filter.summary.Gather
[INFO] 2015-09-08 18:03:09,866 [smrtpipe.status refreshTargets 407] task P_Filter.filter.summary.Gather successfully completed (10.00 sec (0.17 min)). freed 1 slots, using 1 slots.
[INFO] 2015-09-08 18:03:09,866 [smrtpipe.status refreshTargets 409] Workflow Completion Status 10/56 in (         . 17%) tasks completed.
[INFO] 2015-09-08 18:03:14,873 [smrtpipe.status refreshTargets 419] Starting task://016449/P_FilterReports/statsRpt
[INFO] 2015-09-08 18:05:59,617 [smrtpipe.status refreshTargets 407] task P_FilterReports.statsRpt successfully completed (163.00 sec (2.72 min)). freed 1 slots, using 1 slots.
[INFO] 2015-09-08 18:05:59,617 [smrtpipe.status refreshTargets 409] Workflow Completion Status 11/56 in (         . 19%) tasks completed.
[INFO] 2015-09-08 18:06:04,625 [smrtpipe.status refreshTargets 419] Starting task://016449/P_FilterReports/loadingRpt
[INFO] 2015-09-08 18:07:01,689 [smrtpipe.status refreshTargets 407] task P_FilterReports.loadingRpt successfully completed (50.00 sec (0.83 min)). freed 1 slots, using 1 slots.
[INFO] 2015-09-08 18:07:01,689 [smrtpipe.status refreshTargets 409] Workflow Completion Status 12/56 in (        .. 21%) tasks completed.
[INFO] 2015-09-08 18:07:06,696 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Fetch/overviewRpt
[INFO] 2015-09-08 18:07:12,808 [smrtpipe.status refreshTargets 407] task P_Fetch.overviewRpt successfully completed (2.00 sec (0.03 min)). freed 1 slots, using 1 slots.
[INFO] 2015-09-08 18:07:12,808 [smrtpipe.status refreshTargets 409] Workflow Completion Status 13/56 in (        .. 23%) tasks completed.
[INFO] 2015-09-08 18:51:06,404 [smrtpipe.status refreshTargets 407] task P_Filter.subreads_002of002 successfully completed (4331.00 sec (72.18 min)). freed 1 slots, using 0 slots.
[INFO] 2015-09-08 18:51:06,405 [smrtpipe.status refreshTargets 409] Workflow Completion Status 14/56 in (        .. 25%) tasks completed.
[INFO] 2015-09-08 18:51:11,412 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Filter/subreads.subreadFastq.Gather
[INFO] 2015-09-08 18:51:11,413 [smrtpipe.status refreshTargets 419] Starting task://016449/P_Filter/subreads.subreads.Gather
[INFO] 2015-09-08 18:58:01,379 [smrtpipe.status refreshTargets 407] task P_Filter.subreads.subreads.Gather successfully completed (408.00 sec (6.80 min)). freed 1 slots, using 1 slots.
[INFO] 2015-09-08 18:58:01,379 [smrtpipe.status refreshTargets 409] Workflow Completion Status 15/56 in (        .. 26%) tasks completed.
[INFO] 2015-09-08 18:58:06,385 [smrtpipe.status refreshTargets 419] Starting task://016449/P_PreAssemblerDagcon/filterLongReadsByLength
[INFO] 2015-09-08 19:02:02,123 [smrtpipe.status refreshTargets 407] task P_Filter.subreads.subreadFastq.Gather successfully completed (646.00 sec (10.77 min)). freed 1 slots, using 1 slots.
[INFO] 2015-09-08 19:02:02,124 [smrtpipe.status refreshTargets 409] Workflow Completion Status 16/56 in (        .. 28%) tasks completed.
[INFO] 2015-09-08 19:06:15,910 [smrtpipe.status refreshTargets 407] task P_PreAssemblerDagcon.filterLongReadsByLength successfully completed (483.00 sec (8.05 min)). freed 1 slots, using 0 slots.
[INFO] 2015-09-08 19:06:15,910 [smrtpipe.status refreshTargets 409] Workflow Completion Status 17/56 in (       ... 30%) tasks completed.
[INFO] 2015-09-08 19:06:20,917 [smrtpipe.status refreshTargets 419] Starting task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection.target.Scatter
[INFO] 2015-09-08 19:07:54,709 [smrtpipe.status refreshTargets 407] task P_PreAssemblerDagcon.hgapAlignForCorrection.target.Scatter successfully completed (89.00 sec (1.48 min)). freed 1 slots, using 0 slots.
[INFO] 2015-09-08 19:07:54,710 [smrtpipe.status refreshTargets 409] Workflow Completion Status 18/56 in (       ... 32%) tasks completed.
[INFO] 2015-09-08 19:07:59,720 [smrtpipe.status refreshTargets 419] Starting task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection_001of002
[ERROR] 2015-09-09 07:08:04,765 [smrtpipe.status refreshTargets 413] *** Failed task task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection_001of002
[INFO] 2015-09-09 07:08:04,766 [smrtpipe.status execute 627] Found 1 failed tasks.
[INFO] 2015-09-09 07:08:04,767 [smrtpipe.status execute 629] task hgapAlignForCorrection_001of002 FAILED
[ERROR] 2015-09-09 07:08:05,616 [SMRTpipe.SmrtPipeMain run 608] SmrtExit task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection_001of002 Failed
Traceback (most recent call last):
  File "/home/bastian/bin/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 571, in run
    self._runTasks(pModules)
  File "/home/bastian/bin/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 300, in _runTasks
    workflow.execute()
  File "/home/bastian/bin/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeWorkflow.py", line 640, in execute
    raise SmrtExit(str(e))
SmrtExit: SmrtExit task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection_001of002 Failed
[ERROR] 2015-09-09 07:08:05,679 [SMRTpipe.SmrtPipeMain exit 690] SmrtExit task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection_001of002 Failed
[INFO] 2015-09-09 07:08:05,680 [SMRTpipe.SmrtPipeMain exit 692] Beginning exit process
[INFO] 2015-09-09 07:08:05,680 [SMRTpipe.SmrtPipeMain shutdown 716] beginning Shutdown Process
[INFO] 2015-09-09 07:08:05,680 [SMRTpipe.SmrtPipeMain _generate_final_report 651] Writing final TOC page with error message : SmrtExit task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection_001of002 Failed
[INFO] 2015-09-09 07:08:06,260 [SMRTpipe.SmrtPipeMain shutdown 752] Completed shutdown gracefully
[INFO] 2015-09-09 07:08:06,261 [SMRTpipe.SmrtPipeMain exit 702] Sending message Exiting smrtpipe last error: SmrtExit task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection_001of002 Failed
[INFO] 2015-09-09 07:08:06,261 [smrtpipe.status failed 104] Sending Job 016449 failed message 'Exiting smrtpipe last error: SmrtExit task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection_001of002 Failed' to url http://sheldon:8080/smrtportal/api/jobs/016449/status
[INFO] 2015-09-09 07:08:06,997 [SMRTpipe.SmrtPipeMain run 641] completed SmrtPipeMain.run with exit code -1
[INFO] 2015-09-09 07:08:06,998 [root main 335] Failed smrtpipe version v1.87.139483 with exit code -1 in 73604.75 seconds (1226.75 minutes)
```

**Comment by pbjd** [comment]
Additional information located in <job root>/016449/logs/P_PreAssemblerDagcon/hgapAlignForCorrection_001of002.log

**Comment by gedankenstuecke** [comment]
Okay, the corresponding file says

```
Running task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection_001of002 on Linux compute10 3.13.0-62-generic #102-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Started on Tue Sep  8 17:06:39 UTC 2015
Validating existence of Input Files
Successfully found /home/bastian/bin/smrtanalysis/userdata/jobs/016/016449/data/filtered_subreads.fasta
Successfully found /home/bastian/bin/smrtanalysis/userdata/jobs/016/016449/filtered_longreads.chunk001of002.fasta
Successfully validated input files
[INFO] 2015-09-08T19:06:40 [blasr] started.
# Writing stdout and stderr from Popen:
Your job 730786 ("Phga016449") has been submitted
Job 730786 exited because of signal SIGKILL
```

Now the question is: Where can I find the corresponding job-log? ;-)

**Comment by pbjd** [comment]
SIGKILL is indicative of hitting an SGE timeout.   Try splitting your job up with more granularity (e.g., use 6 or more chunks instead of 2).  Also, make sure your nproc settings match your SGE slots requested.  You can see these settings in workflow/P_PreAssemblerDagcon/hgapAlignForCorrection_001of002.sh (nproc) and grep 'hgapAlignForCorrection_001of002.sh' log/master.log, look for `-pe smp <slots requested>'.

**Comment by gedankenstuecke** [comment]
Thanks, the nproc in hgapAlignForCorrection_001of002.sh fits the -pe smp setting. But I'll try splitting it into more chunks and see what happens. Just for clarity: By SGE timeout you mean that the SGE-set limit for how long a single process may run, right?

**Comment by pbjd** [comment]
Right.  By default, I think smrtanalysis is configured to limit them to 12 hours.

**Comment by jkaralius** [comment]
P_PreAssemblerDagcon/hgapAlignForCorrection_001of002 failed with a SIGKILL at 12 hours, see log snippet below:
```
[INFO] 2015-09-08 19:07:59,720 [smrtpipe.status refreshTargets 419] Starting task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection_001of002
[ERROR] 2015-09-09 07:08:04,765 [smrtpipe.status refreshTargets 413] *** Failed task task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection_001of002
```

Try modifying the hard run-time limit `-l h_rt` in `$SMRT_ROOT/current/analysis/etc/cluster/SGE/interactive.tmpl`.
Increasing the value from the default `12:0:0` to something like `120:0:0` should allow enough time to complete.

**Comment by gedankenstuecke** [comment]
Thanks, I'll give that a try!
