### ISSUE TITLE
task hgapAlignForCorrection FAILED 

### ISSUE THREAD

**Issue by sudhirjadhao** [PacificBiosciences/SMRT-Analysis#226]
P_PreAssemblerDagcon.filterLongReadsByLength successfully completed (571.00 sec (9.52 min)). freed 1 slots, using 1 slots.
[INFO] 2015-09-18 15:03:11,787 [smrtpipe.status refreshTargets 409] Workflow Completion Status 131/137 in ( ......... 95%) tasks completed.
[INFO] 2015-09-18 15:03:16,795 [smrtpipe.status refreshTargets 419] Starting task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection
[ERROR] 2015-09-18 15:03:16,796 [smrtpipe.status refreshTargets 413] *** Failed task task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection
[INFO] 2015-09-18 15:53:42,654 [smrtpipe.status execute 627] Found 1 failed tasks.
[INFO] 2015-09-18 15:53:42,654 [smrtpipe.status execute 629] task hgapAlignForCorrection FAILED 
[ERROR] 2015-09-18 15:54:10,390 [SMRTpipe.SmrtPipeMain run 608] SmrtExit task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection Failed
Traceback (most recent call last):
File "/media/9759e2b0-edca-4aaa-a141-110bc7765ca3/SMRT/SMRT_setup/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 571, in run
self._runTasks(pModules)
File "/media/9759e2b0-edca-4aaa-a141-110bc7765ca3/SMRT/SMRT_setup/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 300, in _runTasks
workflow.execute()
File "/media/9759e2b0-edca-4aaa-a141-110bc7765ca3/SMRT/SMRT_setup/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeWorkflow.py", line 640, in execute
raise SmrtExit(str(e))
SmrtExit: SmrtExit task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection Failed
[ERROR] 2015-09-18 15:54:10,392 [SMRTpipe.SmrtPipeMain exit 690] SmrtExit task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection Failed
[INFO] 2015-09-18 15:54:10,392 [SMRTpipe.SmrtPipeMain exit 692] Beginning exit process
[INFO] 2015-09-18 15:54:10,393 [SMRTpipe.SmrtPipeMain shutdown 716] beginning Shutdown Process
[INFO] 2015-09-18 15:54:10,393 [SMRTpipe.SmrtPipeMain _generate_final_report 651] Writing final TOC page with error message : SmrtExit task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection Failed
[INFO] 2015-09-18 15:54:11,348 [SMRTpipe.SmrtPipeMain shutdown 752] Completed shutdown gracefully
[INFO] 2015-09-18 15:54:11,348 [SMRTpipe.SmrtPipeMain exit 702] Sending message Exiting smrtpipe last error: SmrtExit task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection Failed
[INFO] 2015-09-18 15:54:11,349 [smrtpipe.status failed 104] Sending Job 016449 failed message 'Exiting smrtpipe last error: SmrtExit task://016449/P_PreAssemblerDagcon/hgapAlignForCorrection Failed' to url http://10.0.0.101:8080/smrtportal/api/jobs/016449/status
[INFO] 2015-09-18 15:54:11,381 [SMRTpipe.SmrtPipeMain run 641] completed SmrtPipeMain.run with exit code -1
[INFO] 2015-09-18 15:54:11,382 [root main 335] Failed smrtpipe version v1.87.139483 with exit code -1 in 6366.30 seconds (106.10 minutes).

I am new to smrt analysis. pleas help me with this error.
I have given 38 smrt cell input. I am doing preassembly of plat genome

**Comment by ctxchris** [comment]
Are you running the pipeline through a scheduling system? If not, adding the option "--distribute" to the command did the trick for me.

Chris
