### ISSUE TITLE
LAA fails

### ISSUE THREAD

**Issue by eleanorahowe** [PacificBiosciences/SMRT-Analysis#240]
Hi there, 

I've got an LAA sample that fails in doAmpliconAnalysis. Log is below. I'm no expert on the SMRT portal, but our resident expert looked at this and said she'd never seen it before. Other samples from this same run worked fine, and the files look ok to me. 

Thanks much for any input you can offer. 

Eleanor

[INFO] 2015-12-09 17:36:11,872 [root main 269] Starting smrtpipe.py : v1.87.139483
[INFO] 2015-12-09 17:36:11,872 [root main 270] Using Python : v2.7.3
[INFO] 2015-12-09 17:36:11,883 [root main 271] Platform info Linux-2.6.32-504.16.2.el6.x86_64-x86_64-with-redhat-6.7-Santiago
[INFO] 2015-12-09 17:36:11,884 [root main 272] Running on btlsmrt.broadinstitute.org
[INFO] 2015-12-09 17:36:11,885 [root main 273] Process id 35987
[INFO] 2015-12-09 17:36:11,885 [SMRTpipe.pbpy.io.SecondaryConfig _loadFromFile 25] Loading SecondaryConfig from /broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/etc/config.xml
[INFO] 2015-12-09 17:36:11,886 [SMRTpipe.SmrtPipeConfig __autoLoad 113] Loading configuration from /broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/analysis/etc/smrtpipe.rc
[INFO] 2015-12-09 17:36:11,887 [SMRTpipe.SmrtPipeConfig __setAlgorithmParametersPath 212] ALGO_PARAMS key not found in smrtpipe.rc - using latest bundle: /broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09
[INFO] 2015-12-09 17:36:11,905 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /tdts/users/ehowe/MUC1/pacbio/umass12072015/BI-SA-M282/F01_1/Analysis_Results/m151203_223053_42183_c100925712550000001823208005121606_s1_p0.1.bax.h5 1708772873 bytes
[INFO] 2015-12-09 17:36:11,905 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /tdts/users/ehowe/MUC1/pacbio/umass12072015/BI-SA-M282/F01_1/Analysis_Results/m151203_223053_42183_c100925712550000001823208005121606_s1_p0.2.bax.h5 1637116989 bytes
[INFO] 2015-12-09 17:36:11,905 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /tdts/users/ehowe/MUC1/pacbio/umass12072015/BI-SA-M282/F01_1/Analysis_Results/m151203_223053_42183_c100925712550000001823208005121606_s1_p0.3.bax.h5 1724669521 bytes
[INFO] 2015-12-09 17:36:11,905 [smrtpipe.status _sanityCheck 804] Successfully found 3 files in xml:/btl/data/PacBio/userdata/jobs/016/016591/input.xml
[INFO] 2015-12-09 17:36:11,906 [SMRTpipe.pbpy.io.SecondaryConfig _loadFromFile 25] Loading SecondaryConfig from /broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/etc/config.xml
[INFO] 2015-12-09 17:36:11,907 [SMRTpipe.SmrtPipeConfig __autoLoad 113] Loading configuration from /broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/analysis/etc/smrtpipe.rc
[INFO] 2015-12-09 17:36:11,908 [SMRTpipe.SmrtPipeConfig __setAlgorithmParametersPath 212] ALGO_PARAMS key not found in smrtpipe.rc - using latest bundle: /broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09
[INFO] 2015-12-09 17:36:11,908 [SMRTpipe.SmrtPipeContext __init__ 98] SmrtPipeConfig Summary:
TMP = /broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/tmpdir
PROGRESS_URL = http://btlsmrt:8080/smrtportal/api
CLUSTER_MANAGER = SGE
HOST_PORT = 8080
NCHUNKS = 64
ALGO_PARAMS_PATH = /broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09
MAX_SLOTS = 256
ca_distribute.hgap = useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0
CLOUD_LARGE_FILE_CUTOFF = 10MB
SMRTANALYSIS_VERSION = 2.3.0
INPUT_HDF5_EXT = bas.h5
SMRTPIPE_VERSION = 2.3.0.139497
HOST_NAME = btlsmrt
DENOVO_READ_SCOPES = small: 0.15, large:15, huge:1700
NPROC = 1
DENOVO_GENOME_SCOPES = small:100, large:1000, huge:40000
NJOBS = 64
CLOUD = False
REFERENCE_SCOPES = small:10, large:1000, veryLarge:100000, huge:10000000
MAX_THREADS = 8
HEARTBEAT_FREQ = 60
VIS_HOST = btlsmrt
VIS_PORT = 8080
SHARED_DIR = /broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/common/userdata/shared_dir
DEBUG = False
ca_distribute.pb2ca = useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0
SETTINGS_PATH = .
EXIT_ON_FAILURE = True
CLOUD_CHUNKS_PER_PROC = 2
READ_SCOPES = small:3.6, large:100, veryLarge:10000, huge:1000000
MAX_CHUNKS = 64
ASSEMBLY_HOME = /broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/analysis
DATA_ROOT = /mnt
VIS_NAMESPACE =
IPY = ipy -X:ColorfulConsole
TOC_HTML_NAME = index.html
[INFO] 2015-12-09 17:36:11,909 [SMRTpipe.SmrtPipeMain run 465] Successfully found or created TMP dir '/broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/tmpdir'
[INFO] 2015-12-09 17:36:11,940 [SMRTpipe.SmrtPipeContext initializeContext 235] SmrtPipeSettings Summary:
settings loaded from file /
p_ampliconanalysis.fastxByBarcode = False
p_ampliconanalysis.takeN = 0
global.fetch = common/protocols/preprocessing/Fetch.1.xml
p_ampliconanalysis.minLength = 3000
p_ampliconanalysis.trimEnds = 0
global.version = 1
global.control = /btl/data/PacBio/userdata/references/2kb_control
global.name = RS_Long_Amplicon_Analysis
p_ampliconanalysis.maxReads = 2000
p_fetch.description = Sets up inputs
p_ampliconanalysis.description = LongAmpliconAnalysis calls phased consensus sequences from pooled amplicon sequence data. Up to 20 distinct amplicons can be pooled. Reads are clustered into high-level groups, then each group is phased and consensus is called using the Quiver algorithm. Additionally, if the sample is barcoded, separate calls are made for each barcode.
p_ampliconanalysis.doClustering = True
p_fetch.moduleName = P_Fetch
p_ampliconanalysis.ignoreEnds = 0
global.barcode = common/protocols/barcode/NoBarcode.1.xml
p_ampliconanalysis.moduleName = P_AmpliconAnalysis
global.description = (BETA) Determine phased consensus sequences for pooled amplicon data. (Optionally splits reads by barcode if the sample is barcoded.)
global.state = active
p_ampliconanalysis.doPhasing = True
global.amplicon = common/protocols/consensus/LongAmpliconAnalysis.1.xml
[INFO] 2015-12-09 17:36:11,956 [SMRTpipe.SmrtDataService setupOutputDirectories 132] Creating /btl/data/PacBio/userdata/jobs/016/016591/data
[INFO] 2015-12-09 17:36:11,962 [SMRTpipe.SmrtDataService setupOutputDirectories 132] Creating /btl/data/PacBio/userdata/jobs/016/016591/results
[INFO] 2015-12-09 17:36:11,964 [SMRTpipe.SmrtDataService setupOutputDirectories 136] Completed setting up DataServices in /btl/data/PacBio/userdata/jobs/016/016591
[INFO] 2015-12-09 17:36:11,964 [SMRTpipe.SmrtPipeContext initializeContext 257] Input data is [ file//tdts/users/ehowe/MUC1/pacbio/umass12072015/BI-SA-M282/F01_1 ]
[INFO] 2015-12-09 17:36:11,964 [SMRTpipe.SmrtPipeContext initializeContext 261] Configuration override for PROGRESS_URL: Old: --> New: http://btlsmrt:8080/smrtportal/api
[INFO] 2015-12-09 17:36:11,965 [SMRTpipe.SmrtPipeContext initializeContext 274] Changing working directory to /broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/tmpdir/tmpP74yQQ
[INFO] 2015-12-09 17:36:11,967 [SMRTpipe.cluster.ClusterJMS __init__ 197] cluster engine: SGE
template root: /broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/analysis/etc/cluster
temporary dir: /broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/common/userdata/shared_dir/tmpKixrc1
[INFO] 2015-12-09 17:36:12,024 [SMRTpipe.SmrtPipeContext movieFiles 371] Pulling data from tags: *
[INFO] 2015-12-09 17:36:12,024 [SMRTpipe.SmrtPipeContext movieFiles 391] Found /tdts/users/ehowe/MUC1/pacbio/umass12072015/BI-SA-M282/F01_1/Analysis_Results/m151203_223053_42183_c100925712550000001823208005121606_s1_p0.1.bax.h5 (1708772873 bytes)
[INFO] 2015-12-09 17:36:12,024 [SMRTpipe.SmrtPipeContext movieFiles 391] Found /tdts/users/ehowe/MUC1/pacbio/umass12072015/BI-SA-M282/F01_1/Analysis_Results/m151203_223053_42183_c100925712550000001823208005121606_s1_p0.2.bax.h5 (1637116989 bytes)
[INFO] 2015-12-09 17:36:12,024 [SMRTpipe.SmrtPipeContext movieFiles 391] Found /tdts/users/ehowe/MUC1/pacbio/umass12072015/BI-SA-M282/F01_1/Analysis_Results/m151203_223053_42183_c100925712550000001823208005121606_s1_p0.3.bax.h5 (1724669521 bytes)
[INFO] 2015-12-09 17:36:12,193 [SMRTpipe.SmrtPipeMain _getBasVersions 413] Detected basH5 versions set(['-v2.3.0'])
[INFO] 2015-12-09 17:36:12,911 [smrtpipe.status run 503] smrtpipe.py running on btlsmrt
[INFO] 2015-12-09 17:36:12,911 [SMRTpipe.SmrtPipeMain run 506] using Distributed mode with 1 nproc
[INFO] 2015-12-09 17:36:12,911 [smrtpipe.status run 519] SMRT Analysis 2.3.0 / SMRTpipe 1.87.139483
[INFO] 2015-12-09 17:36:12,911 [SMRTpipe.SmrtPipeMain run 522] Starting smrtpipe version 1.87.139483
[INFO] 2015-12-09 17:36:13,625 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_Fetch module
[INFO] 2015-12-09 17:36:13,627 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_Fetch v2.4.139483 and validated settings.
[INFO] 2015-12-09 17:36:13,718 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_AmpliconAnalysis module
[INFO] 2015-12-09 17:36:13,722 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_AmpliconAnalysis v1.12.125061 and validated settings.
[INFO] 2015-12-09 17:36:13,724 [SMRTpipe.SmrtDataService writeTo 424] Writing 6 items to DataStore in {'smrt.data.xmlparam': , 'smrt.output.log': '/btl/data/PacBio/userdata/jobs/016/016591/log', 'smrt.data.cmdline': >, 'smrt.output.root': '/btl/data/PacBio/userdata/jobs/016/016591', 'smrt.output.results': '/btl/data/PacBio/userdata/jobs/016/016591/results', 'smrt.output.data': '/btl/data/PacBio/userdata/jobs/016/016591/data'}
[INFO] 2015-12-09 17:36:13,731 [SMRTpipe.SmrtPipeMain _runTasks 281] Skipping PreWorkflow as it contains zero tasks
[INFO] 2015-12-09 17:36:13,731 [SMRTpipe.SmrtPipeMain _runTasks 284] Loading 6 tasks into Workflow
[INFO] 2015-12-09 17:36:14,510 [SMRTpipe.SmrtPipeMain _runTasks 298] Executing workflow Workflow
[INFO] 2015-12-09 17:36:14,510 [smrtpipe.status execute 620] Process id 35987
[INFO] 2015-12-09 17:36:20,336 [smrtpipe.status refreshTargets 419] Starting task://016591/P_Fetch/toFofn
[INFO] 2015-12-09 17:36:20,348 [smrtpipe.status refreshTargets 407] task P_Fetch.toFofn successfully completed (1.00 sec (0.02 min)). freed 1 slots, using 0 slots.
[INFO] 2015-12-09 17:36:20,348 [smrtpipe.status refreshTargets 409] Workflow Completion Status 1/6 in ( . 16%) tasks completed.
[INFO] 2015-12-09 17:36:25,357 [smrtpipe.status refreshTargets 419] Starting task://016591/P_AmpliconAnalysis/doAmpliconAnalysis
[INFO] 2015-12-09 17:36:25,358 [smrtpipe.status refreshTargets 419] Starting task://016591/P_Fetch/adapterRpt
[INFO] 2015-12-09 17:36:25,358 [smrtpipe.status refreshTargets 419] Starting task://016591/P_Fetch/overviewRpt
[INFO] 2015-12-09 17:36:46,940 [smrtpipe.status refreshTargets 407] task P_Fetch.overviewRpt successfully completed (4.00 sec (0.07 min)). freed 1 slots, using 2 slots.
[INFO] 2015-12-09 17:36:46,941 [smrtpipe.status refreshTargets 409] Workflow Completion Status 2/6 in ( ... 33%) tasks completed.
[INFO] 2015-12-09 17:37:38,660 [smrtpipe.status refreshTargets 407] task P_Fetch.adapterRpt successfully completed (58.00 sec (0.97 min)). freed 1 slots, using 1 slots.
[INFO] 2015-12-09 17:37:38,661 [smrtpipe.status refreshTargets 409] Workflow Completion Status 3/6 in ( ..... 50%) tasks completed.
[ERROR] 2015-12-09 20:01:38,027 [smrtpipe.status refreshTargets 413] *** Failed task task://016591/P_AmpliconAnalysis/doAmpliconAnalysis
[INFO] 2015-12-09 20:01:38,028 [smrtpipe.status execute 627] Found 1 failed tasks.
[INFO] 2015-12-09 20:01:38,029 [smrtpipe.status execute 629] task doAmpliconAnalysis FAILED
[ERROR] 2015-12-09 20:01:38,404 [SMRTpipe.SmrtPipeMain run 608] SmrtExit task://016591/P_AmpliconAnalysis/doAmpliconAnalysis Failed
Traceback (most recent call last):
File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 571, in run
self._runTasks(pModules)
File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 300, in _runTasks
workflow.execute()
File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/smrtanalysis_2.3.0-redhat/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeWorkflow.py", line 640, in execute
raise SmrtExit(str(e))
SmrtExit: SmrtExit task://016591/P_AmpliconAnalysis/doAmpliconAnalysis Failed
[ERROR] 2015-12-09 20:01:38,406 [SMRTpipe.SmrtPipeMain exit 690] SmrtExit task://016591/P_AmpliconAnalysis/doAmpliconAnalysis Failed
[INFO] 2015-12-09 20:01:38,406 [SMRTpipe.SmrtPipeMain exit 692] Beginning exit process
[INFO] 2015-12-09 20:01:38,406 [SMRTpipe.SmrtPipeMain shutdown 716] beginning Shutdown Process
[INFO] 2015-12-09 20:01:38,406 [SMRTpipe.SmrtPipeMain _generate_final_report 651] Writing final TOC page with error message : SmrtExit task://016591/P_AmpliconAnalysis/doAmpliconAnalysis Failed
[INFO] 2015-12-09 20:01:39,193 [SMRTpipe.SmrtPipeMain shutdown 752] Completed shutdown gracefully
[INFO] 2015-12-09 20:01:39,193 [SMRTpipe.SmrtPipeMain exit 702] Sending message Exiting smrtpipe last error: SmrtExit task://016591/P_AmpliconAnalysis/doAmpliconAnalysis Failed
[INFO] 2015-12-09 20:01:39,193 [smrtpipe.status failed 104] Sending Job 016591 failed message 'Exiting smrtpipe last error: SmrtExit task://016591/P_AmpliconAnalysis/doAmpliconAnalysis Failed' to url http://btlsmrt:8080/smrtportal/api/jobs/016591/status
[INFO] 2015-12-09 20:01:39,247 [SMRTpipe.SmrtPipeMain run 641] completed SmrtPipeMain.run with exit code -1
[INFO] 2015-12-09 20:01:39,247 [root main 335] Failed smrtpipe version v1.87.139483 with exit code -1 in 8727.34 seconds (145.46 minutes)

**Comment by eleanorahowe** [comment]
I re-ran the analysis and it worked fine this time. I still don't know why, but I'm happy it worked.
