### ISSUE TITLE
error running pbalign

### ISSUE THREAD

**Issue by conte1** [PacificBiosciences/SMRT-Analysis#243]
I'm running pbalign installed via smrtanalysis_2.3.0.140936 like so:
```pbalign --tmpDir tmp --nproc 24 --forQuiver test.input.fofn ~/work/test/2-asm-falcon/p_ctg.fa test.cmp.h5```

And I'm getting the following error:
*2015-12-21 16:27:23,499 [ERROR] SortService returned a non-zero exit status. Traceback (most recent call last):
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/analysis/bin/cmph5tools.py", line 43, in <module>
    from pbh5tools.CmpH5Select import cmpH5Select
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/pbh5tools/CmpH5Select.py", line 38, in <module>
    import h5py as H5
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/h5py/__init__.py", line 10, in <module>
    from h5py import _errors
ImportError: /sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/h5py/_errors.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8*

If I use the python distribution then I get a different error:
*ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha1
...
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/analysis/bin/cmph5tools.py", line 43, in <module>
    from pbh5tools.CmpH5Select import cmpH5Select
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/pbh5tools/CmpH5Select.py", line 41, in <module>
    from pbcore.io import CmpH5Reader
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/pbcore/io/__init__.py", line 33, in <module>
    from .CmpH5IO import *
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/pbcore/io/CmpH5IO.py", line 44, in <module>
    from pbcore.io.FastaIO import splitFastaHeader
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/pbcore/io/FastaIO.py", line 47, in <module>
    import md5, mmap, numpy as np, re
  File "/sw/SMRT_ANALYSIS/SMRT_ROOT/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/md5.py", line 10, in <module>
    from hashlib import md5
ImportError: cannot import name md5*

**Comment by mhsieh** [comment]
Hi, Are you running this under smrtshell?

**Comment by conte1** [comment]
Initially I was not running this under smrtshell as I running into bash issues on our slurm cluster. I've figured out some workarounds to get things running, but they are pretty ugly. Is slurm support for SMRT analysis planned at all?
