### ISSUE TITLE
P_Fetch/adapterRpt.sh failed weirdly

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/SMRT-Analysis#245]
When I ran `BAM_Resequencing_Beta.1` protocol from smrtportal, the workflow always aborted at `P_Fetch/adapterRpt.sh` (see error below). However, if I enter `$SMRT_ROOT/userdata/jobs/016/JOBID` and execute `workflow/P_Fetch/adapterRpt.sh` directly, the exit code is 0. What went wrong when I ran from smrtportal? Thanks.

```
Traceback (most recent call last):
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbsystem/common/cmdline/core.py", line 19, in args_executer
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 350, in args_runner
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 56, in make_adapter_report
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 210, in to_report_streaming
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 196, in _create_histograms
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 181, in applier
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 159, in calc_untrimmed_adapter_histogram
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 147, in _get_zmw_records
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbcore/io/BasH5IO.py", line 765, in __init__
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbcore/io/BasH5IO.py", line 410, in __init__
IOError: Invalid or nonexistent bax/bas file /home/user/project/pacbio_genome/PACBIO-WIB/01-20150206_68cells/sample_3_iffy/D01_1/Analysis_Results/m150108_190715_42199_c100714972550000001823154504301563_s1_p0.1.bax.h5
```

I also tried to remove the above `bax.h5` file from analysis, and started over, however next time it would stop due to another file. Since there are over a thousand files in input, I cannot test them one by one.

**Comment by yunfeiguo** [comment]
BTW I ran `adapterRpt.sh` with the same user name used to install and launch smrtportal.

**Comment by yunfeiguo** [comment]
I wonder if this error was caused by multiple programs trying to access the same file? Because the error seems to be random, and only occurred during workflow launched by smrtportal but not when only P_Fetch/adapterRpt.sh is running.
