### ISSUE TITLE
Celera assembler run error

### ISSUE THREAD

**Issue by Dave217** [PacificBiosciences/SMRT-Analysis#262]
Twice now I've gotten this error when I try to run a HGAP_Assembly.2 protocol for my de novo assembly.  This is I think the relevant line: 

SmrtExit: SmrtExit task://016439/P_CeleraAssembler/runCaHgap Failed

I'm running version 2.3.0, patch 5, in Bio-linux with 12GB RAM and an 8 core i7-4710HQ.  

Any help would be appreciated.  Any other relevant details I can provide?  In the meantime I'll try another protocol and find a way to record resource usage (in the setup it said that I'm just shy of the required RAM, 1.5 GB/core.  Could this be my issue?)

> [INFO] 2016-04-21 13:14:10,733 [smrtpipe.status refreshTargets 419] Starting task://016439/P_PreAssemblerDagcon/hgapCorrection
[INFO] 2016-04-21 13:41:14,197 [smrtpipe.status refreshTargets 407] task P_PreAssemblerDagcon.hgapCorrection successfully completed (1627.00 sec (27.12 min)). freed 7 slots, using 0 slots.
[INFO] 2016-04-21 13:41:14,197 [smrtpipe.status refreshTargets 409] Workflow Completion Status 22/42 in ( ..... 52%) tasks completed.
[INFO] 2016-04-21 13:41:19,204 [smrtpipe.status refreshTargets 419] Starting task://016439/P_CeleraAssembler/genFrgFile
[INFO] 2016-04-21 13:41:19,205 [smrtpipe.status refreshTargets 419] Starting task://016439/P_CeleraAssembler/writeRunCASpec
[INFO] 2016-04-21 13:41:19,205 [smrtpipe.status refreshTargets 419] Starting task://016439/P_PreAssemblerDagcon/preAssemblerJsonReport
[INFO] 2016-04-21 13:41:19,217 [smrtpipe.status refreshTargets 407] task P_CeleraAssembler.genFrgFile successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 2 slots.
[INFO] 2016-04-21 13:41:19,217 [smrtpipe.status refreshTargets 409] Workflow Completion Status 23/42 in ( ..... 54%) tasks completed.
[INFO] 2016-04-21 13:41:19,952 [smrtpipe.status refreshTargets 407] task P_CeleraAssembler.writeRunCASpec successfully completed (2.00 sec (0.03 min)). freed 1 slots, using 1 slots.
[INFO] 2016-04-21 13:41:19,952 [smrtpipe.status refreshTargets 409] Workflow Completion Status 24/42 in ( ..... 57%) tasks completed.
[INFO] 2016-04-21 13:41:24,981 [smrtpipe.status refreshTargets 419] Starting task://016439/P_CeleraAssembler/runCaHgap
[INFO] 2016-04-21 13:41:30,730 [smrtpipe.status refreshTargets 407] task P_PreAssemblerDagcon.preAssemblerJsonReport successfully completed (13.00 sec (0.22 min)). freed 1 slots, using 1 slots.
[INFO] 2016-04-21 13:41:30,730 [smrtpipe.status refreshTargets 409] Workflow Completion Status 25/42 in ( ..... 59%) tasks completed.
[ERROR] 2016-04-21 13:41:40,741 [smrtpipe.status refreshTargets 413] *** Failed task task://016439/P_CeleraAssembler/runCaHgap
[INFO] 2016-04-21 13:41:40,743 [smrtpipe.status execute 627] Found 1 failed tasks.
[INFO] 2016-04-21 13:41:40,743 [smrtpipe.status execute 629] task runCaHgap FAILED 
[ERROR] 2016-04-21 13:41:41,181 [SMRTpipe.SmrtPipeMain run 608] SmrtExit task://016439/P_CeleraAssembler/runCaHgap Failed
Traceback (most recent call last):
File "/opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 571, in run
self._runTasks(pModules)
File "/opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 300, in _runTasks
workflow.execute()
File "/opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeWorkflow.py", line 640, in execute
raise SmrtExit(str(e))
SmrtExit: SmrtExit task://016439/P_CeleraAssembler/runCaHgap Failed
[ERROR] 2016-04-21 13:41:41,182 [SMRTpipe.SmrtPipeMain exit 690] SmrtExit task://016439/P_CeleraAssembler/runCaHgap Failed
[INFO] 2016-04-21 13:41:41,182 [SMRTpipe.SmrtPipeMain exit 692] Beginning exit process
[INFO] 2016-04-21 13:41:41,183 [SMRTpipe.SmrtPipeMain shutdown 716] beginning Shutdown Process
[INFO] 2016-04-21 13:41:41,183 [SMRTpipe.SmrtPipeMain _generate_final_report 651] Writing final TOC page with error message : SmrtExit task://016439/P_CeleraAssembler/runCaHgap Failed
[INFO] 2016-04-21 13:41:41,578 [SMRTpipe.SmrtPipeMain shutdown 752] Completed shutdown gracefully
[INFO] 2016-04-21 13:41:41,578 [SMRTpipe.SmrtPipeMain exit 702] Sending message Exiting smrtpipe last error: SmrtExit task://016439/P_CeleraAssembler/runCaHgap Failed
[INFO] 2016-04-21 13:41:41,578 [smrtpipe.status failed 104] Sending Job 016439 failed message 'Exiting smrtpipe last error: SmrtExit task://016439/P_CeleraAssembler/runCaHgap Failed' to url http://10.90.51.220:2222/smrtportal/api/jobs/016439/status
[INFO] 2016-04-21 13:41:41,667 [SMRTpipe.SmrtPipeMain run 641] completed SmrtPipeMain.run with exit code -1
[INFO] 2016-04-21 13:41:41,668 [root main 335] Failed smrtpipe version v1.87.139483 with exit code -1 in 8312.96 seconds (138.55 minutes)

**Comment by jordash92** [comment]
I've just had the exact same error. Similarly I'm running version 2.3.0 on BioLinux. A previous assembly worked great against a reference genome using RS_Resequencing.1. Also unsure to what the problem is here. I'm only got 5GB RAM. Have you tired any other protocols or managed to fix the issue yet?

Jordan

**Comment by zendl0r** [comment]
I also encountered this error when I was testing the new installation of version 2.3.0 with the patch 5 with the Lambda data and the RS_HGAP_Assembly.2. 
I changed the assembly settings to: 
       Minimum Seed Read Length*: 1000
       Genome Size (bp)*: 40.000

> [INFO] 2016-11-24 13:18:41,719 [smrtpipe.status refreshTargets 407] task P_CeleraAssembler.writeRunCASpec successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 1 slots.
[INFO] 2016-11-24 13:18:41,719 [smrtpipe.status refreshTargets 409] Workflow Completion Status 24/42 in ( ..... 57%) tasks completed.
[INFO] 2016-11-24 13:18:42,787 [smrtpipe.status refreshTargets 407] task P_PreAssemblerDagcon.preAssemblerJsonReport successfully completed (1.00 sec (0.02 min)). freed 1 slots, using 0 slots.
[INFO] 2016-11-24 13:18:42,787 [smrtpipe.status refreshTargets 409] Workflow Completion Status 25/42 in ( ..... 59%) tasks completed.
[INFO] 2016-11-24 13:18:47,793 [smrtpipe.status refreshTargets 419] Starting task://016446/P_CeleraAssembler/runCaHgap
[ERROR] 2016-11-24 13:22:36,419 [smrtpipe.status refreshTargets 413] *** Failed task task://016446/P_CeleraAssembler/runCaHgap
[INFO] 2016-11-24 13:22:36,420 [smrtpipe.status execute 627] Found 1 failed tasks.
[INFO] 2016-11-24 13:22:36,421 [smrtpipe.status execute 629] task runCaHgap FAILED
[ERROR] 2016-11-24 13:22:36,957 [SMRTpipe.SmrtPipeMain run 608] SmrtExit task://016446/P_CeleraAssembler/runCaHgap Failed
Traceback (most recent call last):
File "/home/smrtanalysis/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 571, in run
self._runTasks(pModules)
File "/home/smrtanalysis/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 300, in _runTasks
workflow.execute()
File "/home/smrtanalysis/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeWorkflow.py", line 640, in execute
raise SmrtExit(str(e))
SmrtExit: SmrtExit task://016446/P_CeleraAssembler/runCaHgap Failed
[ERROR] 2016-11-24 13:22:36,958 [SMRTpipe.SmrtPipeMain exit 690] SmrtExit task://016446/P_CeleraAssembler/runCaHgap Failed

The RS_Resequencing.1 did work fine. Are there any news what the problem might be?

**Comment by jordash92** [comment]
It was a memory issue for me. Copied my VM to another machine where I gave it about 30GB RAM and it worked fine.

**Comment by zendl0r** [comment]
Hm so my workstation is running Ubunutu 12.04 and has an 8 core i7 processor and 8 gb of ram. This should meet the requirements but i will try and upgrade the ram if this is the solution for the problem :)

**Comment by jordash92** [comment]
Upgrading your ram is definitely the way to go. What are you assembling? (just being nosy).

**Comment by zendl0r** [comment]
Then the IT-department will have something to do tomorrow :)
I'm trying to reassemble a pool of BAC clones because we missed the vector trimming in the first place.
