### ISSUE TITLE
Runing  smrtanalysis_2.3.0.140936 (with patch 5)  "P_Filter Failed"  problems

### ISSUE THREAD

**Issue by starsyi** [PacificBiosciences/SMRT-Analysis#267]
hi,
I'm try to filter my data, but I got some problems. I have no idea where is wrong.
my smrtanalysis version is smrtanalysis_2.3.0.140936 and smrtanalysis-patch_2.3.0.140936.p5
this is the first time to run it after I install smrtanalysis. 

```
[INFO] 2016-05-09 22:53:20,735 [root main 269] Starting smrtpipe.py : v1.87.139483
[INFO] 2016-05-09 22:53:20,735 [root main 270] Using Python         : v2.7.3
[INFO] 2016-05-09 22:53:20,766 [root main 271] Platform info Linux-2.6.32-504.el6.x86_64-x86_64-with-centos-6.6-Final
[INFO] 2016-05-09 22:53:20,767 [root main 272] Running on comput22
[INFO] 2016-05-09 22:53:20,767 [root main 273] Process id 20375
[INFO] 2016-05-09 22:53:20,767 [SMRTpipe.pbpy.io.SecondaryConfig _loadFromFile 25] Loading SecondaryConfig from /public/home/xxyi/bin/smrtanalysis/current/etc/config.xml
[INFO] 2016-05-09 22:53:20,795 [SMRTpipe.SmrtPipeConfig __autoLoad 113] Loading configuration from /public/home/xxyi/bin/smrtanalysis/current/analysis/etc/smrtpipe.rc
[INFO] 2016-05-09 22:53:20,797 [SMRTpipe.SmrtPipeConfig __setAlgorithmParametersPath 212] ALGO_PARAMS key not found in smrtpipe.rc - using latest bundle: /public/home/xxyi/bin/smrtanalysis/current/analysis/etc/algorithm_parameters/2015-11
[INFO] 2016-05-09 22:53:20,799 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /public/home/xxyi/data/E_coli/E01_1/Analysis_Results/m141013_011508_sherri_c100709962550000001823135904221533_s1_p0.3.bax.h5 3268151141 bytes
[INFO] 2016-05-09 22:53:20,800 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /public/home/xxyi/data/E_coli/E01_1/Analysis_Results/m141013_011508_sherri_c100709962550000001823135904221533_s1_p0.1.bax.h5 2884273052 bytes
[INFO] 2016-05-09 22:53:20,801 [SMRTpipe.SmrtPipeMain _sanityCheck 796] Found file /public/home/xxyi/data/E_coli/E01_1/Analysis_Results/m141013_011508_sherri_c100709962550000001823135904221533_s1_p0.2.bax.h5 3466682889 bytes
[INFO] 2016-05-09 22:53:20,801 [smrtpipe.status _sanityCheck 804] Successfully found 3 files in xml:input.xml
[INFO] 2016-05-09 22:53:20,801 [SMRTpipe.pbpy.io.SecondaryConfig _loadFromFile 25] Loading SecondaryConfig from /public/home/xxyi/bin/smrtanalysis/current/etc/config.xml
[INFO] 2016-05-09 22:53:20,801 [SMRTpipe.SmrtPipeConfig __autoLoad 113] Loading configuration from /public/home/xxyi/bin/smrtanalysis/current/analysis/etc/smrtpipe.rc
[INFO] 2016-05-09 22:53:20,802 [SMRTpipe.SmrtPipeConfig __setAlgorithmParametersPath 212] ALGO_PARAMS key not found in smrtpipe.rc - using latest bundle: /public/home/xxyi/bin/smrtanalysis/current/analysis/etc/algorithm_parameters/2015-11
[INFO] 2016-05-09 22:53:20,802 [SMRTpipe.SmrtPipeContext __init__ 98] SmrtPipeConfig Summary:
                         TMP = /public/home/xxyi/bin/smrtanalysis/tmpdir                                                      
                PROGRESS_URL =                                                                                                
             CLUSTER_MANAGER = PBS                                                                                            
                   HOST_PORT = 8080                                                                                           
                     NCHUNKS = 64                                                                                             
            ALGO_PARAMS_PATH = /public/home/xxyi/bin/smrtanalysis/current/analysis/etc/algorithm_parameters/2015-11           
                   MAX_SLOTS = 256                                                                                            
          ca_distribute.hgap = useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0                                    
     CLOUD_LARGE_FILE_CUTOFF = 10MB                                                                                           
        SMRTANALYSIS_VERSION = 2.3.0                                                                                          
              INPUT_HDF5_EXT = bas.h5                                                                                         
            SMRTPIPE_VERSION = 2.3.0.139497                                                                                   
                   HOST_NAME = 211.69.143.174                                                                                 
          DENOVO_READ_SCOPES = small: 0.15, large:15, huge:1700                                                               
                       NPROC = 31                                                                                             
        DENOVO_GENOME_SCOPES = small:100, large:1000, huge:40000                                                              
                       NJOBS = 64                                                                                             
                       CLOUD = False                                                                                          
            REFERENCE_SCOPES = small:10, large:1000, veryLarge:100000, huge:10000000                                          
                 MAX_THREADS = 8                                                                                              
              HEARTBEAT_FREQ = 60                                                                                             
                    VIS_HOST = 211.69.143.174                                                                                 
                    VIS_PORT = 8080                                                                                           
                  SHARED_DIR = /public/home/xxyi/bin/smrtanalysis/install/smrtanalysis_2.3.0.140936/common/userdata/shared_dir
                       DEBUG = False                                                                                          
         ca_distribute.pb2ca = useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0                                    
               SETTINGS_PATH = .                                                                                              
             EXIT_ON_FAILURE = True                                                                                           
       CLOUD_CHUNKS_PER_PROC = 2                                                                                              
                 READ_SCOPES = small:3.6, large:100, veryLarge:10000, huge:1000000                                            
                  MAX_CHUNKS = 64                                                                                             
               ASSEMBLY_HOME = /public/home/xxyi/bin/smrtanalysis/current/analysis                                            
                   DATA_ROOT = /mnt                                                                                           
               VIS_NAMESPACE =                                                                                                
                         IPY = ipy -X:ColorfulConsole                                                                         
               TOC_HTML_NAME = index.html                                                                                     
[INFO] 2016-05-09 22:53:20,809 [SMRTpipe.SmrtPipeMain run 465] Successfully found or created TMP dir '/public/home/xxyi/bin/smrtanalysis/tmpdir'
[INFO] 2016-05-09 22:53:20,824 [SMRTpipe.SmrtPipeContext initializeContext 235] SmrtPipeSettings Summary:
settings loaded from file /public/home/xxyi/data/E_coli/result/filter
             p_filter.readScore = 0.80                                                                                            
             p_filter.minLength = 100                                                                                             
            p_filter.moduleName = P_Filter                                                                                        
      p_filter.minSubReadLength = 500                                                                                             
           p_filter.description = Filter reads for use in the pre-assembly step of HGAP, the hierarchical genome assembly process.
     p_filterreports.moduleName = P_FilterReports                                                                                 
[INFO] 2016-05-09 22:53:20,826 [SMRTpipe.SmrtDataService setupOutputDirectories 132] Creating /public/home/xxyi/data/E_coli/result/filter/data
[INFO] 2016-05-09 22:53:20,827 [SMRTpipe.SmrtDataService setupOutputDirectories 132] Creating /public/home/xxyi/data/E_coli/result/filter/results
[INFO] 2016-05-09 22:53:20,829 [SMRTpipe.SmrtDataService setupOutputDirectories 136] Completed setting up DataServices in /public/home/xxyi/data/E_coli/result/filter
[INFO] 2016-05-09 22:53:20,829 [SMRTpipe.SmrtPipeContext initializeContext 257] Input data is [ run/0000000-0002, run/0000000-0000, run/0000000-0001 ]
[INFO] 2016-05-09 22:53:20,852 [SMRTpipe.SmrtPipeContext movieFiles 371] Pulling data from tags: *
[INFO] 2016-05-09 22:53:20,852 [SMRTpipe.SmrtPipeContext movieFiles 391] Found /public/home/xxyi/data/E_coli/E01_1/Analysis_Results/m141013_011508_sherri_c100709962550000001823135904221533_s1_p0.3.bax.h5 (3268151141 bytes)
[INFO] 2016-05-09 22:53:20,852 [SMRTpipe.SmrtPipeContext movieFiles 391] Found /public/home/xxyi/data/E_coli/E01_1/Analysis_Results/m141013_011508_sherri_c100709962550000001823135904221533_s1_p0.1.bax.h5 (2884273052 bytes)
[INFO] 2016-05-09 22:53:20,853 [SMRTpipe.SmrtPipeContext movieFiles 391] Found /public/home/xxyi/data/E_coli/E01_1/Analysis_Results/m141013_011508_sherri_c100709962550000001823135904221533_s1_p0.2.bax.h5 (3466682889 bytes)
[INFO] 2016-05-09 22:53:21,094 [SMRTpipe.SmrtPipeMain _getBasVersions 413] Detected basH5 versions set(['-v2.3.0'])
[INFO] 2016-05-09 22:53:22,668 [smrtpipe.status run 503] smrtpipe.py running on comput22
[INFO] 2016-05-09 22:53:22,668 [smrtpipe.status run 519] SMRT Analysis 2.3.0 / SMRTpipe 1.87.139483
[INFO] 2016-05-09 22:53:22,669 [SMRTpipe.SmrtPipeMain run 522] Starting smrtpipe version 1.87.139483
[INFO] 2016-05-09 22:53:23,521 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_Filter module
[INFO] 2016-05-09 22:53:23,524 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_Filter v1.7.139483 and validated settings.
[INFO] 2016-05-09 22:53:23,526 [SMRTpipe.SmrtPipeMain _dynamicallyLoadModule 846] Dynamically Loaded P_FilterReports module
[INFO] 2016-05-09 22:53:23,527 [SMRTpipe.SmrtPipeMain _loadModules 212] Loaded module P_FilterReports v1.21.139483 and validated settings.
[INFO] 2016-05-09 22:53:23,528 [SMRTpipe.SmrtDataService writeTo 424] Writing 6 items to DataStore in {'smrt.data.xmlparam': <InputDataUrl ref:PreAssemblerSFilter.1.xml >, 'smrt.output.log': '/public/home/xxyi/data/E_coli/result/filter/log', 'smrt.data.cmdline': <CompositeInputData url:xml:input.xml job:None >, 'smrt.output.root': '/public/home/xxyi/data/E_coli/result/filter', 'smrt.output.results': '/public/home/xxyi/data/E_coli/result/filter/results', 'smrt.output.data': '/public/home/xxyi/data/E_coli/result/filter/data'}
[INFO] 2016-05-09 22:53:23,536 [SMRTpipe.SmrtPipeMain _runTasks 281] Skipping PreWorkflow as it contains zero tasks
[INFO] 2016-05-09 22:53:23,537 [SMRTpipe.SmrtPipeMain _runTasks 284] Loading 6 tasks into Workflow
[INFO] 2016-05-09 22:53:24,323 [SMRTpipe.SmrtPipeMain _runTasks 298] Executing workflow Workflow
[INFO] 2016-05-09 22:53:24,323 [smrtpipe.status execute 620] Process id 20375
[INFO] 2016-05-09 22:53:30,663 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/filter.plsFofn.Scatter
[INFO] 2016-05-09 22:53:30,664 [smrtpipe.status refreshTargets 407] task P_Filter.filter.plsFofn.Scatter successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 0 slots.
[INFO] 2016-05-09 22:53:30,664 [smrtpipe.status refreshTargets 409] Workflow Completion Status 1/15 in (            6%) tasks completed.
[INFO] 2016-05-09 22:53:35,673 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/filter_001of003
[INFO] 2016-05-09 22:53:35,675 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/filter_003of003
[INFO] 2016-05-09 22:53:35,676 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/filter_002of003
[INFO] 2016-05-09 22:53:55,697 [smrtpipe.status refreshTargets 407] task P_Filter.filter_001of003 successfully completed (24.00 sec (0.40 min)). freed 2 slots, using 4 slots.
[INFO] 2016-05-09 22:53:55,697 [smrtpipe.status refreshTargets 409] Workflow Completion Status 2/15 in (         . 13%) tasks completed.
[INFO] 2016-05-09 22:53:55,698 [smrtpipe.status refreshTargets 407] task P_Filter.filter_002of003 successfully completed (25.00 sec (0.42 min)). freed 2 slots, using 2 slots.
[INFO] 2016-05-09 22:53:55,698 [smrtpipe.status refreshTargets 409] Workflow Completion Status 3/15 in (        .. 20%) tasks completed.
[INFO] 2016-05-09 22:54:00,704 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/subreads_001of003
[INFO] 2016-05-09 22:54:00,704 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/subreads_002of003
[INFO] 2016-05-09 22:54:00,706 [smrtpipe.status refreshTargets 407] task P_Filter.filter_003of003 successfully completed (25.00 sec (0.42 min)). freed 2 slots, using 2 slots.
[INFO] 2016-05-09 22:54:00,706 [smrtpipe.status refreshTargets 409] Workflow Completion Status 4/15 in (        .. 26%) tasks completed.
[INFO] 2016-05-09 22:54:05,713 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/filter.summary.Gather
[INFO] 2016-05-09 22:54:05,713 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/subreads_003of003
[INFO] 2016-05-09 22:54:05,714 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/filter.rgnFofn.Gather
[INFO] 2016-05-09 22:54:05,715 [smrtpipe.status refreshTargets 407] task P_Filter.filter.rgnFofn.Gather successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 4 slots.
[INFO] 2016-05-09 22:54:05,715 [smrtpipe.status refreshTargets 409] Workflow Completion Status 5/15 in (       ... 33%) tasks completed.
[INFO] 2016-05-09 22:54:06,769 [smrtpipe.status refreshTargets 407] task P_Filter.filter.summary.Gather successfully completed (1.00 sec (0.02 min)). freed 1 slots, using 3 slots.
[INFO] 2016-05-09 22:54:06,769 [smrtpipe.status refreshTargets 409] Workflow Completion Status 6/15 in (      .... 40%) tasks completed.
[INFO] 2016-05-09 22:54:11,775 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_FilterReports/statsRpt
[INFO] 2016-05-09 22:54:11,776 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_FilterReports/loadingRpt
[INFO] 2016-05-09 22:54:11,776 [smrtpipe.status refreshTargets 419] Starting task://Anonymous/P_Filter/subreadSummary
[ERROR] 2016-05-09 22:54:11,776 [smrtpipe.status refreshTargets 413] *** Failed task task://Anonymous/P_FilterReports/statsRpt
[ERROR] 2016-05-09 22:54:11,776 [smrtpipe.status refreshTargets 413] *** Failed task task://Anonymous/P_FilterReports/loadingRpt
[INFO] 2016-05-09 22:56:58,145 [smrtpipe.status execute 627] Found 2 failed tasks.
[INFO] 2016-05-09 22:56:58,148 [smrtpipe.status execute 629] task loadingRpt FAILED 
[INFO] 2016-05-09 22:56:58,149 [smrtpipe.status execute 629] task statsRpt FAILED 
[ERROR] 2016-05-09 22:56:59,601 [SMRTpipe.SmrtPipeMain run 608] SmrtExit task://Anonymous/P_FilterReports/loadingRpt Failed task://Anonymous/P_FilterReports/statsRpt Failed
Traceback (most recent call last):
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 571, in run
    self._runTasks(pModules)
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 300, in _runTasks
    workflow.execute()
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeWorkflow.py", line 640, in execute
    raise SmrtExit(str(e))
SmrtExit: SmrtExit task://Anonymous/P_FilterReports/loadingRpt Failed task://Anonymous/P_FilterReports/statsRpt Failed
[ERROR] 2016-05-09 22:56:59,604 [SMRTpipe.SmrtPipeMain exit 690] SmrtExit task://Anonymous/P_FilterReports/loadingRpt Failed task://Anonymous/P_FilterReports/statsRpt Failed
[INFO] 2016-05-09 22:56:59,604 [SMRTpipe.SmrtPipeMain exit 692] Beginning exit process
[INFO] 2016-05-09 22:56:59,604 [SMRTpipe.SmrtPipeMain shutdown 716] beginning Shutdown Process
[INFO] 2016-05-09 22:56:59,604 [SMRTpipe.SmrtPipeMain _generate_final_report 651] Writing final TOC page with error message : SmrtExit task://Anonymous/P_FilterReports/loadingRpt Failed task://Anonymous/P_FilterReports/statsRpt Failed
[INFO] 2016-05-09 22:57:00,722 [SMRTpipe.SmrtPipeMain shutdown 752] Completed shutdown gracefully
[INFO] 2016-05-09 22:57:00,722 [SMRTpipe.SmrtPipeMain exit 702] Sending message Exiting smrtpipe last error: SmrtExit task://Anonymous/P_FilterReports/loadingRpt Failed task://Anonymous/P_FilterReports/statsRpt Failed
[INFO] 2016-05-09 22:57:00,728 [SMRTpipe.SmrtPipeMain run 641] completed SmrtPipeMain.run with exit code -1
[INFO] 2016-05-09 22:57:00,728 [root main 335] Failed smrtpipe version v1.87.139483 with exit code -1 in 219.93 seconds (3.67 minutes)
```

**Comment by starsyi** [comment]
**and this is  my  _log/P_FilterReports/statsRpt.log_ file**

```
#!/bin/bash
# Setting up SMRTpipe environment
echo "Setting up ENV on $(uname -n)" for task statsRpt

SEYMOUR_HOME=/public/home/xxyi/bin/smrtanalysis/current
source $SEYMOUR_HOME/etc/setup.sh

# Create the local TMP dir if it doesn't exist
tmp_dir=$(readlink -m "/public/home/xxyi/bin/smrtanalysis/tmpdir")
if [ ! -e "$tmp_dir" ]; then
   stat=0
   mkdir -p $tmp_dir || stat=$?
   if [[ $stat -ne 0 ]]; then
       echo "SMRTpipe Unable to create TMP dir '/public/home/xxyi/bin/smrtanalysis/tmpdir' on $(uname -n)" 1>&2
       exit 1
   else
       echo "successfully created or found TMP dir '/public/home/xxyi/bin/smrtanalysis/tmpdir'"
   fi
elif [[ ! -d "$tmp_dir" ]]; then
   echo "SMRTpipe TMP /public/home/xxyi/bin/smrtanalysis/tmpdir must be a directory on $(uname -n)" 1>&2
   exit 1
fi

########### TASK metadata #############
# Task            : statsRpt
# Module          : P_FilterReports
# Module Version  : 1.21.139483
# TaskType        : None
# URL             : task://Anonymous/P_FilterReports/statsRpt
# createdAt       : 2016-05-11 14:51:47.686881
# createdAt (UTC) : 2016-05-11 06:51:47.686907
# ncmds           : 2
# LogPath         : /public/home/xxyi/data/E_coli/result/filter/log/P_FilterReports/statsRpt.log
# Script Path     : /public/home/xxyi/data/E_coli/result/filter/workflow/P_FilterReports/statsRpt.sh

# Input       : /public/home/xxyi/data/E_coli/result/filter/data/filtered_summary.csv
# Output      : /public/home/xxyi/data/E_coli/result/filter/results/filter_reports_filter_stats.json
#
########### END TASK metadata #############

cd /public/home/xxyi/data/E_coli/result/filter/log/P_FilterReports
# Writing to log file
cat /public/home/xxyi/data/E_coli/result/filter/workflow/P_FilterReports/statsRpt.sh >> /public/home/xxyi/data/E_coli/result/filter/log/P_FilterReports/statsRpt.log;



echo "Running task://Anonymous/P_FilterReports/statsRpt on $(uname -a)"

echo "Started on $(date -u)"
echo 'Validating existence of Input Files'
if [ -e /public/home/xxyi/data/E_coli/result/filter/data/filtered_summary.csv ]
then
echo 'Successfully found /public/home/xxyi/data/E_coli/result/filter/data/filtered_summary.csv'
else
echo 'WARNING: Unable to find necessary input file, or dir /public/home/xxyi/data/E_coli/result/filter/data/filtered_summary.csv.'
fi
echo 'Successfully validated input files'

# Task statsRpt commands:


# Completed writing Task statsRpt commands


# Task 1
filter_stats.py --debug --output=/public/home/xxyi/data/E_coli/result/filter/results --report=/public/home/xxyi/data/E_coli/result/filter/results/filter_reports_filter_stats.json /public/home/xxyi/data/E_coli/result/filter/data/filtered_summary.csv || exit $?
echo "Task 1 completed at $(date)"
# Task 2
smrtreporter -basedir /public/home/xxyi/data/E_coli/result/filter/results -headinclude /public/home/xxyi/data/E_coli/result/filter/results/.martin_header.html --html -o filter_reports_filter_stats.html -rules /public/home/xxyi/data/E_coli/result/filter/results/.rules_filter_reports_filter_stats.xml || exit $?
echo "Task 2 completed at $(date)"



rcode=$?
echo "Finished on $(date -u)"
echo "Task statsRpt with nproc 1 with exit code ${rcode}."
exit ${rcode}# Writing stdout and stderr from Popen:
Setting up ENV on login for task statsRpt
Running task://Anonymous/P_FilterReports/statsRpt on Linux login 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Started on Wed May 11 06:52:32 UTC 2016
Validating existence of Input Files
Successfully found /public/home/xxyi/data/E_coli/result/filter/data/filtered_summary.csv
Successfully validated input files
Traceback (most recent call last):
  File "/public/home/xxyi/bin/smrtanalysis/current/analysis/bin/filter_stats.py", line 8, in <module>
    load_entry_point('pbreports==2.3', 'console_scripts', 'filter_stats.py')()
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 318, in load_entry_point
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2221, in load_entry_point
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1954, in load
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbreports/report/filter_stats.py", line 15, in <module>
    from pbreports.plot.helper import get_green, get_blue
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbreports/plot/helper.py", line 5, in <module>
    import matplotlib.pyplot as plt
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 764, in <module>
    rcParams = rc_params()
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 682, in rc_params
    fname = matplotlib_fname()
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 595, in matplotlib_fname
    fname = os.path.join(get_configdir(), 'matplotlibrc')
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 248, in wrapper
    ret = func(*args, **kwargs)
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 470, in _get_configdir
    if not _is_writable_dir(h):
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 178, in _is_writable_dir
    t.close()
IOError: [Errno 2] No such file or directory
```

**and this is my _log/P_FilterReports/loadingRpt.log_ file**

```
#!/bin/bash
# Setting up SMRTpipe environment
echo "Setting up ENV on $(uname -n)" for task loadingRpt

SEYMOUR_HOME=/public/home/xxyi/bin/smrtanalysis/current
source $SEYMOUR_HOME/etc/setup.sh

# Create the local TMP dir if it doesn't exist
tmp_dir=$(readlink -m "/public/home/xxyi/bin/smrtanalysis/tmpdir")
if [ ! -e "$tmp_dir" ]; then
   stat=0
   mkdir -p $tmp_dir || stat=$?
   if [[ $stat -ne 0 ]]; then
       echo "SMRTpipe Unable to create TMP dir '/public/home/xxyi/bin/smrtanalysis/tmpdir' on $(uname -n)" 1>&2
       exit 1
   else
       echo "successfully created or found TMP dir '/public/home/xxyi/bin/smrtanalysis/tmpdir'"
   fi
elif [[ ! -d "$tmp_dir" ]]; then
   echo "SMRTpipe TMP /public/home/xxyi/bin/smrtanalysis/tmpdir must be a directory on $(uname -n)" 1>&2
   exit 1
fi

########### TASK metadata #############
# Task            : loadingRpt
# Module          : P_FilterReports
# Module Version  : 1.21.139483
# TaskType        : None
# URL             : task://Anonymous/P_FilterReports/loadingRpt
# createdAt       : 2016-05-11 14:51:47.483746
# createdAt (UTC) : 2016-05-11 06:51:47.483770
# ncmds           : 2
# LogPath         : /public/home/xxyi/data/E_coli/result/filter/log/P_FilterReports/loadingRpt.log
# Script Path     : /public/home/xxyi/data/E_coli/result/filter/workflow/P_FilterReports/loadingRpt.sh

# Input       : /public/home/xxyi/data/E_coli/result/filter/data/filtered_summary.csv
# Output      : /public/home/xxyi/data/E_coli/result/filter/results/filter_reports_loading.json
#
########### END TASK metadata #############

cd /public/home/xxyi/data/E_coli/result/filter/log/P_FilterReports
# Writing to log file
cat /public/home/xxyi/data/E_coli/result/filter/workflow/P_FilterReports/loadingRpt.sh >> /public/home/xxyi/data/E_coli/result/filter/log/P_FilterReports/loadingRpt.log;



echo "Running task://Anonymous/P_FilterReports/loadingRpt on $(uname -a)"

echo "Started on $(date -u)"
echo 'Validating existence of Input Files'
if [ -e /public/home/xxyi/data/E_coli/result/filter/data/filtered_summary.csv ]
then
echo 'Successfully found /public/home/xxyi/data/E_coli/result/filter/data/filtered_summary.csv'
else
echo 'WARNING: Unable to find necessary input file, or dir /public/home/xxyi/data/E_coli/result/filter/data/filtered_summary.csv.'
fi
echo 'Successfully validated input files'

# Task loadingRpt commands:


# Completed writing Task loadingRpt commands


# Task 1
pbreport.py loading --debug /public/home/xxyi/data/E_coli/result/filter/results filter_reports_loading.json /public/home/xxyi/data/E_coli/result/filter/data/filtered_summary.csv || exit $?
echo "Task 1 completed at $(date)"
# Task 2
smrtreporter -basedir /public/home/xxyi/data/E_coli/result/filter/results -headinclude /public/home/xxyi/data/E_coli/result/filter/results/.martin_header.html --html -o filter_reports_loading.html -rules /public/home/xxyi/data/E_coli/result/filter/results/.rules_filter_reports_loading.xml || exit $?
echo "Task 2 completed at $(date)"



rcode=$?
echo "Finished on $(date -u)"
echo "Task loadingRpt with nproc 1 with exit code ${rcode}."
exit ${rcode}# Writing stdout and stderr from Popen:
Setting up ENV on login for task loadingRpt
Running task://Anonymous/P_FilterReports/loadingRpt on Linux login 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Started on Wed May 11 06:52:32 UTC 2016
Validating existence of Input Files
Successfully found /public/home/xxyi/data/E_coli/result/filter/data/filtered_summary.csv
Successfully validated input files
Traceback (most recent call last):
  File "/public/home/xxyi/bin/smrtanalysis/current/analysis/bin/pbreport.py", line 9, in <module>
    import pbreports.report.adapter
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 17, in <module>
    from pbreports.plot.helper import (get_fig_axes_lpr, apply_histogram_data,
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbreports/plot/helper.py", line 5, in <module>
    import matplotlib.pyplot as plt
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 764, in <module>
    rcParams = rc_params()
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 682, in rc_params
    fname = matplotlib_fname()
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 595, in matplotlib_fname
    fname = os.path.join(get_configdir(), 'matplotlibrc')
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 248, in wrapper
    ret = func(*args, **kwargs)
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 470, in _get_configdir
    if not _is_writable_dir(h):
  File "/public/home/xxyi/bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 178, in _is_writable_dir
    t.close()
IOError: [Errno 2] No such file or directory
```

**Comment by starsyi** [comment]
@pb-jlandolin hope you can help me. I really need your help
