### ISSUE TITLE
Running pbtranscript.py cluster with errors

### ISSUE THREAD

**Issue by Ginsea** [PacificBiosciences/SMRT-Analysis#270]
Dear Dr.
I used pbtranscript.py to perform isoform level clustering analysis with the following command "pbtranscript.py cluster isoseq_flnc.fasta final.consensus.fa   --nfl_fa isoseq_nfl.fasta -d cluster --ccs_fofn reads_of_insert.fofn   --bas_fofn input.fofn --cDNA_size under1k --quiver --use_sge    --max_sge_jobs 40 --unique_id 300 --blasr_nproc 24 --quiver_nproc 8   --nfl_fa isoseq_nfl.fasta".

While the terminal told me that "2016-05-17 14:39:56,103 [ERROR] Exiting pbtranscript with return code 1.
Traceback (most recent call last):
  File "/share/nas2/workdir/lius/software/smrtanalysis/current/analysis/bin/pbtranscript.py", line 146, in run
    obj.run()
  File "/share/nas2/workdir/lius/software/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/Cluster.py", line 245, in run
    fastq_filename=first_split_fq)
  File "/share/nas2/workdir/lius/software/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 95, in __init__
    sanity_check_sge(self.script_dir)
  File "/share/nas2/workdir/lius/software/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceUtils.py", line 81, in sanity_check_sge
    if not filecmp.cmp(consensusFa, GCON_OUT_FA):
  File "/share/nas2/workdir/lius/software/smrtanalysis/current/redist/python2.7/lib/python2.7/filecmp.py", line 42, in cmp
    s1 = _sig(os.stat(f1))
OSError: [Errno 2] No such file or directory: '/share/nas2/workdir/chenzx/kiwi_pacbio/test_cluster/cluster/scripts/gcon_test_dir/g_consensus.fa'"

In the cluster folder, the software divided input file into four parts, while only the first part have ".self.blasr" and ".fastq" file, just like this:

(smrtanalysis-2.3.0) [chenzx@compute-0-3 cluster]$ ls
init.uc.pickle     input.split_00.fa.self.blasr  input.split_01.fa  input.split_03.fa  output              scripts
input.split_00.fa  input.split_00.fastq          input.split_02.fa  log                run_ice_config.txt  tmp

Thanks!

**Comment by anjalianjali1234** [comment]
any solution... I am having the same error...
