### ISSUE TITLE
smrt 2.3 smrtpipe.py ImportError, but I source $SMRT_ROOT/current/etc/setup.sh 

### ISSUE THREAD

**Issue by xiehaiy** [PacificBiosciences/SMRT-Analysis#284]
```py
(smrtanalysis-2.3.0) [PGII5@RCBB HGAP_test]$ [INFO] 2016-08-03 14:49:30,275 Successfully found 1 files in xml:input.xml
[INFO] 2016-08-03 14:49:32,951 smrtpipe.py running on RCBB
[INFO] 2016-08-03 14:49:32,951 SMRT Analysis 2.3.0 / SMRTpipe 1.87.139483
Traceback (most recent call last):
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 184, in _loadModules
    instance = _dynamicallyLoadModule(moduleName)
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 844, in _dynamicallyLoadModule
    klass = _dynamic_pbinternal_importer(moduleName, upbpy_s)
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 821, in _dynamic_pbinternal_importer
    m = __import__(s)
ImportError: No module named pbinternal.smrtpipe.modules.Assembly
Failed smrtpipe version v1.87.139483 with exit code -1 in 6.42 seconds (0.11 minutes)
```

**Comment by pb-cdunn** [comment]
@xiehaiy, how did you resolve this? Even if it was something trivial, that might help others in the future.

**Comment by xiehaiy** [comment]
oh, my --params=params.xml is wrong
