### ISSUE TITLE
quiver is successfully install, but fail to run.

### ISSUE THREAD

**Issue by fs07313** [PacificBiosciences/SMRT-Analysis#318]
I followed this website [How to install and use Quiver] (http://bioinfo-master.ird.fr:8080/smrtanalysis/doc/bioinformatics-tools/GenomicConsensus/doc/HowToQuiver.html) to install quiver. It can be installed successfully. When I run it, it gives the error information below. Can anyone tell me how to work around it? Thanks!

 (VE-QUIVER) [fs@localhost VE-QUIVER]$ quiver -h
Traceback (most recent call last):
  File "/home/fs/software/fs_virtualenv/VE-QUIVER/bin/variantCaller", line 4, in <module>
    __import__('pkg_resources').run_script('GenomicConsensus==2.1.0', 'variantCaller')
  File "/home/fs/software/fs_virtualenv/VE-QUIVER/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/fs/software/fs_virtualenv/VE-QUIVER/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/home/fs/software/fs_virtualenv/VE-QUIVER/lib/python2.7/site-packages/GenomicConsensus-2.1.0-py2.7.egg/EGG-INFO/scripts/variantCaller", line 5, in <module>
    sys.exit(main())
  File "/home/fs/software/fs_virtualenv/VE-QUIVER/lib/python2.7/site-packages/GenomicConsensus-2.1.0-py2.7.egg/GenomicConsensus/main.py", line 419, in main
    parser=get_parser(),
  File "/home/fs/software/fs_virtualenv/VE-QUIVER/lib/python2.7/site-packages/GenomicConsensus-2.1.0-py2.7.egg/GenomicConsensus/options.py", line 127, in get_parser
    tcp.add_choice_str(
AttributeError: 'ToolContractParser' object has no attribute 'add_choice_str'

**Comment by sohnjangil** [comment]
I have similar problems...

Traceback (most recent call last):
  File "/home/physicon/Programs/Python/Python-2.7.13/bin/variantCaller", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/physicon/Programs/GenomicConsensus/bin/variantCaller", line 5, in <module>
    sys.exit(main())
  File "/home/physicon/Programs/GenomicConsensus/GenomicConsensus/main.py", line 419, in main
    parser=get_parser(),
  File "/home/physicon/Programs/GenomicConsensus/GenomicConsensus/options.py", line 127, in get_parser
    tcp.add_choice_str(
AttributeError: 'ToolContractParser' object has no attribute 'add_choice_str'

**Comment by bananabenana** [comment]
Hey all, the workaround is an update. Not sure exactly what was outdated, but something was.

I did:

`sudo apt-get update&&sudo apt-get install &&sudo apt-get dist-upgrade && sudo apt-get autoclean && sudo apt-get clean && sudo apt-get autoremove`
