### ISSUE TITLE
P_Control failure: Unable to parse bax.h5 filename

### ISSUE THREAD

**Issue by robsyme** [PacificBiosciences/SMRT-Analysis#321]
While running the "Modification and Motif Analysis" pipeline through the smrtanalysis web interface, my jobs fail.

The smrtpipe.stderr points to the P_Control module:

```
Traceback (most recent call last):
  File "/ppgdata/applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeWorkflow.py", line 634, in execute
    raise WorkflowError(_e_msg)
WorkflowError: task://016438/P_Control/summaryCSV Failed
```

The file userdata/jobs/016/016438/log/P_Control/summaryCSV.log reports:

```
[INFO] 2017-04-03 20:18:24,377 [pbreports.report.summarize_compare_by_movie _get_movie_stats_from_movie_files 517] <MovieStats m150527_095515_42158_c100818552550000001823172611031503_s1_p0 chip:0000 instrument:42158 set:s1 part:p0 type:NA date:150527 >
[INFO] 2017-04-03 20:18:24,377 [pbreports.report.summarize_compare_by_movie _get_movie_stats_from_movie_files 515] Getting movie stats from /data/path/XSECU_20141016_RS42150_PL100044940A-2_A01-2.1/Analysis_Results/XSECU_20141016_RS42150_PL100044940A-2_A01-2.1.2.bax.h5
[ERROR] 2017-04-03 20:18:24,377 [pbreports.report.summarize_compare_by_movie main 750] Unable to parse /data/path/XSECU_20141016_RS42150_PL100044940A-2_A01-2.1/Analysis_Results/XSECU_20141016_RS42150_PL100044940A-2_A01-2.1.2.bax.h5 with (m\d{6}_\d{6}_[A-Z,a-z]{3}_p(\d|\d{2})_b(\d{2}|\d)).(pls|bas|rgn).h5
Traceback (most recent call last):
  File "/ppgdata/applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbreports/report/summarize_compare_by_movie.py", line 747, in main
    rcode = run(cmp_h5, movie_files, output_csv, external_mode=external_mode)
  File "/ppgdata/applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbreports/report/summarize_compare_by_movie.py", line 692, in run
    allMovies = _get_movie_stats_from_movie_files(movie_files)
  File "/ppgdata/applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbreports/report/summarize_compare_by_movie.py", line 516, in _get_movie_stats_from_movie_files
    movie_stat = _movie_file_name_to_movie_stat(movie_file)
  File "/ppgdata/applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbreports/report/summarize_compare_by_movie.py", line 664, in _movie_file_name_to_movie_stat
    movie_stat = __movie_astro_name_to_movie_stat(file_name)
  File "/ppgdata/applications/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbreports/report/summarize_compare_by_movie.py", line 642, in __movie_astro_name_to_movie_stat
    raise MovieParseException("Unable to parse {f} with {p}".format(**_d))
MovieParseException: Unable to parse /data/path/XSECU_20141016_RS42150_PL100044940A-2_A01-2.1/Analysis_Results/XSECU_20141016_RS42150_PL100044940A-2_A01-2.1.2.bax.h5 with (m\d{6}_\d{6}_[A-Z,a-z]{3}_p(\d|\d{2})_b(\d{2}|\d)).(pls|bas|rgn).h5
Unable to parse /data/path/XSECU_20141016_RS42150_PL100044940A-2_A01-2.1/Analysis_Results/XSECU_20141016_RS42150_PL100044940A-2_A01-2.1.2.bax.h5 with (m\d{6}_\d{6}_[A-Z,a-z]{3}_p(\d|\d{2})_b(\d{2}|\d)).(pls|bas|rgn).h5
[INFO] 2017-04-03 20:18:24,377 [pbreports.report.summarize_compare_by_movie main 756] completed summarize_compare_by_movie.py v2.0 with exit code -1 in 0.00 sec.
```

Crucially, the failure seems to occur when trying to match the filename `XSECU_20141016_RS42150_PL100044940A-2_A01-2.1.2.bax.h5` with the regex: 
`(m\d{6}_\d{6}_[A-Z,a-z]{3}_p(\d|\d{2})_b(\d{2}|\d)).(pls|bas|rgn).h5`

which fails.

The files in that folder are:

```
$ tree /data/path/XSECU_20141016_RS42150_PL100044940A-2_A01-2.1/
/data/path/XSECU_20141016_RS42150_PL100044940A-2_A01-2.1/
├── Analysis_Results
│   ├── XSECU_20141016_RS42150_PL100044940A-2_A01-2.1.1.bax.h5
│   ├── XSECU_20141016_RS42150_PL100044940A-2_A01-2.1.2.bax.h5
│   ├── XSECU_20141016_RS42150_PL100044940A-2_A01-2.1.3.bax.h5
│   └── XSECU_20141016_RS42150_PL100044940A-2_A01-2.1.bas.h5
└── XSECU_20141016_RS42150_PL100044940A-2_A01-2.1.metadata.xml
```
I'm using some old and some new data. The older data has filenames as above, and the newer data has filename like:

```
tree /data/path/Pacbio-3
/data/path/Pacbio-3
├── Analysis_Results
│   ├── m150527_225805_42158_c100818552550000001823172611031506_s1_p0.1.bax.h5
│   ├── m150527_225805_42158_c100818552550000001823172611031506_s1_p0.2.bax.h5
│   ├── m150527_225805_42158_c100818552550000001823172611031506_s1_p0.3.bax.h5
│   └── m150527_225805_42158_c100818552550000001823172611031506_s1_p0.bas.h5
└── m150527_225805_42158_c100818552550000001823172611031506_s1_p0.metadata.xml
```
Is there something wrong with the way I've set up my data? 

Thanks!

**Comment by robsyme** [comment]
I see that in `analysis/lib/python2.7/pbreports/report/summarize_compare_by_movie.py`, there are a number of different formats:
 - `(m\d{6}_\d{6}_.+_c[0-9]{32}[0-7]_s(1|2)_(p|X)0).(1|2|3).(pls|bax|bas|rgn).h5`, then
 - `(m\d{6}_\d{6}_.+_c[0-9]{32}[0-7]_s(1|2)_(p|X)0).(pls|bas|rgn).h5`, then finally
 - `(m\d{6}_\d{6}_[A-Z,a-z]{3}_p(\d|\d{2})_b(\d{2}|\d)).(pls|bas|rgn).h5`

And the older data I have doesn't match any of these filename formats. perhaps the PacBio data is simply too old to use?

**Comment by mhsieh** [comment]
My guess is that you should be able to find its original filenames from metadata.xml file and rename them back.

**Comment by robsyme** [comment]
Good thinking.

For a `metadata.xml` that looks like this:

```
<Metadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://pacificbiosciences.com/PAP/Metadata.xsd">
  <InstCtrlVer>2.3.0.0.140640</InstCtrlVer>
  <SigProcVer>
    NRT@172.31.128.10:8082, SwVer=2300.140640, HwVer=1.0
  </SigProcVer>
  <Run>
    <RunId>r000510_42150_141016</RunId>
    <Name>20141016_RS42150_1</Name>
    <WhenCreated>2014-10-16T13:03:23</WhenCreated>
    <WhenStarted>2014-10-16T13:08:04</WhenStarted>
  </Run>
  <Movie>
    <WhenStarted>2014-10-16T15:30:26.836727+00:00</WhenStarted>
    <DurationInSec>10800</DurationInSec>
    <Number>0</Number>
  </Movie>
  <Sample>
    <Name>PS100044940A-1</Name>
    <PlateId>20141016_RS42150_1</PlateId>
    <WellName>A01</WellName>
    <Concentration>0</Concentration>
    <SampleReuseEnabled>false</SampleReuseEnabled>
    <StageHotstartEnabled>true</StageHotstartEnabled>
    <SizeSelectionEnabled>false</SizeSelectionEnabled>
    <UseCount>1</UseCount>
    <Comments/>
  </Sample>
  <InstrumentId>1</InstrumentId>
  <InstrumentName>42150</InstrumentName>
  <CollectionProtocol>MagBead Standard Seq v2</CollectionProtocol>
  <CollectionNumber>1</CollectionNumber>
  <CellIndex>6</CellIndex>
  <SetNumber>1</SetNumber>
  ...
</Metadata>
```

The filenames should be:
- `m141016_153026_42150_c10072658255000000182315100430150_s1_p0.1.bax.h5`
- `m141016_153026_42150_c10072658255000000182315100430150_s1_p0.2.bax.h5`
- `m141016_153026_42150_c10072658255000000182315100430150_s1_p0.3.bax.h5`

right?

In my newer reads, there doesn't seem to be a perfect match between the date_time captured by regex at the start of the filename and the timestamp recorded in the Metadata/Movie/WhenStarted XML node. For example, in the file `m150527_225805_42158_c100818552550000001823172611031506_s1_p0.1.bax.h5` above, the `WhenStarted` field in xml is `2015-05-27T23:07:51.936584+00:00`
. Are these date_time captures used for anything where accuracy is super important?
