### ISSUE TITLE
pbbarcode error

### ISSUE THREAD

**Issue by bioprog** [PacificBiosciences/SMRT-Analysis#331]
Hi,
I have downloaded the .run file to install SMRT analysis 2.3
I have already used ./ConsensusTools.sh which worked fine. But when I try to use ./pbbarcode I get the following error:
```
$ ./pbbarcode --help
Traceback (most recent call last):
  File "./pbbarcode", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pbbarcode==0.8.0' distribution was not found and is required by the application
```

**Comment by bioprog** [comment]
Here's what I had to do:
Download pbbarcode from github -> make install
Still errors: AlignmentFile not found. Apparently my pysam is not up to date. "pip install pysam" results in 0.7.7. So I downloaded the 0.11.2 release from github.
In order to build and install pysam I had to get the libraries libbz2-dev and liblzma-dev.
Still didn't work. Last step was to download pbh5tools from github. No install instructions available but from looking into the Makefile I figured that a simple "make" would do it.
After all of this, pbbarcode is now ready to use.
I still do not understand why:
1) pbbarcode ist not installed after running that smrtanalysis.run file
2) all the dependencies are not resolved
