### ISSUE TITLE
Ubuntu : problem during v2.3.0 installation on ubuntu 17

### ISSUE THREAD

**Issue by Lcornet** [PacificBiosciences/SMRT-Analysis#347]
I try to install the smrt portal on my Linux Station and it crash.
here is the error message:
```
tarting database server...
  Successfully started database server (pid: 8376)...
mysqld is alive
Securing the database...
Creating the jms.setup.sh file...
Creating the user.settings file...
Creating the user.smrtpipe.rc file...
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/home/lcornet/Documents/Program/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/lcornet/Documents/Program/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md5
....
```
And this is my setting : 
```
Applying these settings:
   # ----- Part 1 of 7: SMRT Analysis User -----
   smrt_user=lcornet
   smrt_group=lcornet
   # ----- Part 2 of 7: System Prerequisite Check -----
   # ----- Part 3 of 7: SMRT Portal DNS ------
   smrtportal_dnsname=139.165.152.231
   # ----- Part 4 of 7: SMRT Portal Webserver  -----
   smrtportal_mainport=8080
   smrtportal_shutdownport=8005
   # ----- Part 5 of 6: Directory setup -----
   g_dirs_tmpdir_link=/home/lcornet/Documents/Program/smrtanalysis/tmpdir
   g_dirs_tmpdir_dest=/tmp/smrtanalysis
   dirs_shared_dir=/home/lcornet/Documents/Program/smrtanalysis/install/smrtanalysis_2.3.0.140936/common/userdata/shared_dir
   dirs_userdata_dir=/home/lcornet/Documents/Program/smrtanalysis/userdata
   # ----- Part 6 of 7: SMRT Portal Database -----
   smrtportal_dbuser_admin=root
   smrtportal_dbpasswd_admin=
   smrtportal_dbuser_smrtportal=smrtportal
   smrtportal_dbpasswd_smrtportal=smrtportal
   smrtportal_dbname=smrtportal
   smrtportal_dbhost=127.0.0.1
   smrtportal_dbport=53306
   smrtportal_namedpipeonly=
   # ----- Part 7 of 7: Job Management Cluster Setup -----
   jms_type=BASH
   jms_jobsaredistributed=false
   jms_ca_distribute_pb2ca=useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0
   jms_ca_distribute_hgap=useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0
   jms_numprocs=31
   sge_root=
   sge_cell=
   jms_bindir=
   jms_queue=
   sge_pe=
   sge_ca_queue=
   sge_ca_pe=
   sge_use_settings_file=false
```
Ubuntu 17 is not supported but it not seems to be the problem, Could you help me ?

**Comment by armintoepfer** [comment]
I'm sorry that I personally can't help you with that problem, but I recommend contacting pacbio tech support: https://www.pacb.com/support/technical-support/

**Comment by jkaralius** [comment]
@Lcornet ,
SMRT Portal v2.3.0 is not supported on Ubuntu 17.
